// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MongoBulkOp 描述一次批量写操作。
 */
export interface MongoBulkOp {
    /**
     * insert | update | updateMany | replace | delete | deleteMany
     */
    "type": string;

    /**
     * JSON
     */
    "filter": string;

    /**
     * JSON
     */
    "document": string;
    "upsert": boolean;
}

/**
 * MongoFindResult 查询结果。
 */
export interface MongoFindResult {
    /**
     * Extended JSON 字符串数组
     */
    "documents": string[] | null;
    "count": number;
    "total": number;
    "durationMs": number;
}

/**
 * MongoQuerySpec 描述一次结构化查询，由前端查询构建器生成。
 */
export interface MongoQuerySpec {
    "database": string;
    "collection": string;

    /**
     * JSON
     */
    "filter": string;

    /**
     * JSON
     */
    "projection": string;

    /**
     * JSON
     */
    "sort": string;
    "limit": number;
    "skip": number;

    /**
     * 索引名或 JSON
     */
    "hint": string;

    /**
     * JSON
     */
    "collation": string;
}

/**
 * MongoTxOp 事务中的一个操作。
 */
export interface MongoTxOp {
    /**
     * insert | update | updateMany | delete | deleteMany | replace
     */
    "type": string;
    "database": string;
    "collection": string;
    "filter": string;
    "document": string;
    "upsert": boolean;
}

/**
 * MongoURIInfo 是连接串解析结果，供前端回填表单。
 */
export interface MongoURIInfo {
    "scheme": string;
    "hosts": string[] | null;
    "username": string;
    "password": string;
    "database": string;
    "authSource": string;
    "authMech": string;
    "replicaSet": string;
    "tls": boolean;
    "srv": boolean;
    "options": { [_ in string]?: string } | null;
}
