// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Skill {
    "name": string;
    "description": string;
    "instructions": string;
    "tools"?: string[] | null;
    "context"?: string;
    "path"?: string;
}
