// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    K8sApplyResult,
    K8sConfigMapInfo,
    K8sContainerSummary,
    K8sDeleteResult,
    K8sDeploymentInfo,
    K8sIngressInfo,
    K8sNamespaceInfo,
    K8sNodeInfo,
    K8sOverview,
    K8sPVCInfo,
    K8sPodInfo,
    K8sSecretInfo,
    K8sServiceInfo,
    KubeconfigContextInfo
} from "./models.js";
