// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * K8sApplyResult 描述 YAML 部署单个资源的结果。
 */
export interface K8sApplyResult {
    "kind": string;
    "name": string;
    "namespace"?: string;

    /**
     * "created" | "configured" | "failed"
     */
    "action": string;
    "message"?: string;
}

/**
 * K8sConfigMapInfo 描述 ConfigMap 配置信息。
 */
export interface K8sConfigMapInfo {
    "name": string;
    "namespace": string;
    "dataCount": number;
    "data"?: { [_ in string]?: string } | null;
    "createdAt": string;
}

/**
 * K8sContainerSummary 描述 Pod 内容器状态。
 */
export interface K8sContainerSummary {
    "name": string;
    "image": string;
    "ready": boolean;

    /**
     * running | waiting | terminated
     */
    "state": string;
    "reason"?: string;
    "restartCount": number;
    "isInit"?: boolean;
}

/**
 * K8sDeploymentInfo 描述 Deployment 无状态负载信息。
 */
export interface K8sDeploymentInfo {
    "name": string;
    "namespace": string;
    "replicas": number;
    "readyReplicas": number;
    "availableReplicas": number;
    "updatedReplicas": number;
    "images": string[] | null;
    "selector"?: { [_ in string]?: string } | null;
    "createdAt": string;
}

/**
 * K8sIngressInfo 描述 Ingress 路由规则信息。
 */
export interface K8sIngressInfo {
    "name": string;
    "namespace": string;
    "ingressClass": string;
    "hosts": string[] | null;
    "rules": string[] | null;
    "createdAt": string;
}

/**
 * K8sNamespaceInfo 描述命名空间信息。
 */
export interface K8sNamespaceInfo {
    "name": string;

    /**
     * Active | Terminating
     */
    "status": string;
    "createdAt": string;
    "labels"?: { [_ in string]?: string } | null;
}

/**
 * K8sNodeInfo 描述集群节点信息。
 */
export interface K8sNodeInfo {
    "name": string;

    /**
     * Ready | NotReady | Unknown
     */
    "status": string;

    /**
     * control-plane | worker | master
     */
    "roles": string;
    "kubeletVersion": string;
    "osImage": string;
    "kernelVersion": string;
    "internalIp": string;
    "externalIp": string;
    "cpuCapacity": string;
    "memCapacity": string;
    "podsCapacity": string;
    "createdAt": string;
    "labels"?: { [_ in string]?: string } | null;
}

/**
 * K8sOverview 描述 Kubernetes 集群的概览信息。
 */
export interface K8sOverview {
    "connected": boolean;
    "apiServer": string;
    "gitVersion": string;
    "platform": string;
    "nodesTotal": number;
    "nodesReady": number;
    "namespacesTotal": number;
    "podsTotal": number;
    "podsRunning": number;
    "deploymentsTotal": number;
    "servicesTotal": number;
}

/**
 * K8sPVCInfo 描述持久卷声明信息。
 */
export interface K8sPVCInfo {
    "name": string;
    "namespace": string;

    /**
     * Bound | Pending | Lost
     */
    "status": string;
    "volumeName": string;
    "capacity": string;
    "accessModes": string[] | null;
    "storageClass": string;
    "createdAt": string;
}

/**
 * K8sPodInfo 描述 Pod 实例信息。
 */
export interface K8sPodInfo {
    "name": string;
    "namespace": string;

    /**
     * Running | Pending | Succeeded | Failed | CrashLoopBackOff
     */
    "status": string;

    /**
     * e.g. "1/1"
     */
    "ready": string;
    "restarts": number;
    "nodeName": string;
    "hostIp"?: string;
    "ip": string;
    "containers": K8sContainerSummary[] | null;
    "createdAt": string;
    "age": string;
}

/**
 * K8sSecretInfo 描述 Secret 凭据信息。
 */
export interface K8sSecretInfo {
    "name": string;
    "namespace": string;
    "type": string;
    "dataCount": number;
    "keys": string[] | null;
    "createdAt": string;
}

/**
 * K8sServiceInfo 描述 Service 网络服务信息。
 */
export interface K8sServiceInfo {
    "name": string;
    "namespace": string;

    /**
     * ClusterIP | NodePort | LoadBalancer | ExternalName
     */
    "type": string;
    "clusterIp": string;
    "externalIp": string;
    "ports": string[] | null;
    "selector"?: { [_ in string]?: string } | null;
    "createdAt": string;
}

/**
 * KubeconfigContextInfo 描述解析出来的 Kubeconfig 上下文及集群信息。
 */
export interface KubeconfigContextInfo {
    "currentContext": string;
    "contexts": string[] | null;
    "clusterHost": string;
}
