// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SessionItem {
    "id": string;
    "title": string;
    "created_at": number;
    "updated_at": number;
}
