// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AuditLogItem {
    "id": number;
    "trace_id": string;
    "session_id": string;
    "tool": string;
    "input": string;

    /**
     * allow | confirm | escalate | forbidden
     */
    "decision": string;
    "output_head": string;
    "duration_ms": number;
    "created_at": number;
}

export interface JobItem {
    "id": string;
    "session_id": string;
    "kind": string;

    /**
     * pending | running | waiting_approval | completed | failed | killed
     */
    "state": string;
    "progress": number;
    "error"?: string;
    "summary"?: string;
    "created_at": number;
    "started_at": number;
    "finished_at": number;
}

export interface JobOutputItem {
    "job_id": string;
    "seq": number;
    "chunk": string;
}

export interface SessionItem {
    "id": string;
    "title": string;
    "workspace": string;

    /**
     * JSON snapshot
     */
    "settings": string;
    "created_at": number;
    "updated_at": number;
}

export interface SubagentItem {
    "id": string;
    "parent_id"?: string;
    "session_id": string;
    "prompt": string;
    "state": string;

    /**
     * JSON
     */
    "result"?: string;
    "depth": number;
    "created_at": number;
    "finished_at": number;
}
