// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DockerComposeDeployReq 用于创建或更新 Compose 项目。
 */
export interface DockerComposeDeployReq {
    /**
     * 客户端生成的 UUID
     */
    "id"?: string;
    "projectName": string;
    "yamlContent": string;
    "envVars": { [_ in string]?: string } | null;
    "forcePull": boolean;
    "recreate": boolean;
}

/**
 * DockerComposeServiceInfo 表示 Stack 内单个服务的运行状态。
 */
export interface DockerComposeServiceInfo {
    "serviceName": string;
    "containerId": string;
    "shortId": string;
    "containerName": string;
    "image": string;

    /**
     * running, exited, paused, dead
     */
    "state": string;
    "status": string;
    "ports": string;
    "health": string;
}

/**
 * DockerComposeStackInfo 表示一个 Compose 项目（Stack）的聚合状态信息。
 */
export interface DockerComposeStackInfo {
    /**
     * 客户端关联的本地 UUID
     */
    "uuid"?: string;
    "name": string;

    /**
     * running, partially_running, stopped
     */
    "status": string;
    "runningServices": number;
    "totalServices": number;
    "services": DockerComposeServiceInfo[] | null;
    "configFiles": string;
    "yamlContent": string;
    "createdAt": string;
}

/**
 * DockerContainerInfo 描述容器信息。
 */
export interface DockerContainerInfo {
    "id": string;
    "shortId": string;
    "names": string[] | null;
    "name": string;
    "image": string;
    "imageId": string;
    "command": string;
    "created": number;

    /**
     * running | exited | paused | restarting | created | dead
     */
    "state": string;

    /**
     * e.g. "Up 2 hours", "Exited (0) 5 minutes ago"
     */
    "status": string;
    "ports": DockerPortMapping[] | null;
    "portStr": string;
    "ipAddress": string;
    "sizeRw"?: number;
    "sizeRootFs"?: number;
    "labels"?: { [_ in string]?: string } | null;
}

/**
 * DockerCreateContainerReq 创建容器参数。
 */
export interface DockerCreateContainerReq {
    "name": string;
    "image": string;
    "cmd"?: string[] | null;
    "env"?: string[] | null;

    /**
     * e.g. "8080:80", "5432:5432/tcp"
     */
    "ports"?: string[] | null;

    /**
     * e.g. "/host/data:/container/data", "vol_name:/app"
     */
    "volumes"?: string[] | null;

    /**
     * no | always | unless-stopped | on-failure
     */
    "restartPolicy"?: string;
    "autoRemove"?: boolean;

    /**
     * bridge | host | none | custom
     */
    "networkMode"?: string;

    /**
     * MB
     */
    "memoryLimit"?: number;
    "cpuShares"?: number;
    "labels"?: { [_ in string]?: string } | null;
}

/**
 * DockerImageInfo 描述镜像信息。
 */
export interface DockerImageInfo {
    "id": string;
    "shortId": string;
    "repoTags": string[] | null;
    "repository": string;
    "tag": string;
    "size": number;
    "sizeStr": string;
    "created": number;
    "containers": number;
    "labels"?: { [_ in string]?: string } | null;
}

/**
 * DockerNetworkInfo 描述网络信息。
 */
export interface DockerNetworkInfo {
    "id": string;
    "shortId": string;
    "name": string;
    "driver": string;
    "scope": string;
    "internal": boolean;
    "enableIPv6": boolean;
    "subnet": string;
    "gateway": string;

    /**
     * containerID -> name/ip
     */
    "containers"?: { [_ in string]?: string } | null;
    "labels"?: { [_ in string]?: string } | null;
}

/**
 * DockerOverview 描述 Docker 守护进程与系统概览信息。
 */
export interface DockerOverview {
    "connected": boolean;
    "serverVersion": string;
    "apiVersion": string;
    "os": string;
    "arch": string;
    "kernelVersion": string;
    "operatingSystem": string;
    "ncpu": number;
    "memTotal": number;
    "containersTotal": number;
    "containersRunning": number;
    "containersPaused": number;
    "containersStopped": number;
    "imagesTotal": number;
    "composeTotal": number;
    "volumesTotal": number;
    "networksTotal": number;
    "dockerRootDir": string;
    "storageDriver": string;
    "endpointType": string;
    "endpointTarget": string;
}

/**
 * DockerPortMapping 端口映射。
 */
export interface DockerPortMapping {
    "ip"?: string;
    "privatePort": number;
    "publicPort"?: number;

    /**
     * tcp | udp
     */
    "type": string;
}

/**
 * DockerPruneReport 清理结果报告。
 */
export interface DockerPruneReport {
    "containersDeleted": string[] | null;
    "imagesDeleted": string[] | null;
    "volumesDeleted": string[] | null;
    "networksDeleted": string[] | null;
    "spaceReclaimed": number;
    "spaceReclaimedStr": string;
}

/**
 * DockerVolumeInfo 描述数据卷信息。
 */
export interface DockerVolumeInfo {
    "name": string;
    "driver": string;
    "scope": string;
    "mountpoint": string;
    "createdAt": string;
    "labels"?: { [_ in string]?: string } | null;
    "size"?: number;
    "refCount"?: number;
}
