// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Value represents a single raw JSON value, which may be one of the following:
 *   - a JSON literal (i.e., null, true, or false)
 *   - a JSON string (e.g., "hello, world!")
 *   - a JSON number (e.g., 123.456)
 *   - an entire JSON object (e.g., {"fizz":"buzz"} )
 *   - an entire JSON array (e.g., [1,2,3] )
 * 
 * Value can represent entire array or object values, while [Token] cannot.
 * Value may contain leading and/or trailing whitespace.
 */
export type Value = any;
