// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

export interface Plan {
    "id": string;
    "session_id": string;
    "objective": string;
    "steps": PlanStep[] | null;
    "risk_level": RiskLevel;
    "need_confirm": boolean;
    "reasoning_content"?: string;
    "created_at": number;
}

export interface PlanStep {
    "id": string;

    /**
     * tool_call | subagent | job | workflow | ask_user
     */
    "action": string;
    "tool_name"?: string;
    "args": json$0.RawMessage;
    "description": string;
    "depends_on"?: string[] | null;
    "expected_out"?: string;
    "exempted"?: boolean;

    /**
     * pending | running | completed | failed | skipped
     */
    "status": string;
    "duration_ms"?: number;
    "error"?: string;
    "output"?: any;
    "verdict"?: string;
}

export enum RiskLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RiskLow = "low",
    RiskMedium = "medium",
    RiskHigh = "high",
};
