// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WikiCatalogItem 紧凑目录清单项，用于 System Prompt 注入与极速索引
 */
export interface WikiCatalogItem {
    "rel_path": string;
    "title": string;
    "summary": string;
    "updated_at": number;
}

/**
 * WikiNode 树状导航节点定义 (与通用树组件对齐)
 */
export interface WikiNode {
    "id": string;
    "name": string;
    "rel_path": string;
    "is_folder": boolean;
    "size"?: number;
    "updated_at": number;
    "children"?: WikiNode[] | null;
}
