// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DirListing 是一次目录读取的结果。
 */
export interface DirListing {
    "path": string;
    "parent": string;
    "items": FileItem[] | null;
}

/**
 * FileItem 是远程目录中的一个条目。
 */
export interface FileItem {
    "name": string;
    "path": string;
    "isDir": boolean;
    "isLink": boolean;
    "size": number;
    "mode": string;
    "modTime": number;
}

export interface SSHCPUInfo {
    "usagePercent": number;
    "cores": number;
    "loadAvg": number[] | null;
}

export interface SSHCronItem {
    "id": string;
    "expression": string;
    "command": string;
    "enabled": boolean;
    "comment": string;
}

export interface SSHDashboardInfo {
    "hostname": string;
    "os": string;
    "uptime": string;
    "cpu": SSHCPUInfo;
    "mem": SSHMemInfo;
    "disks": SSHDiskInfo[] | null;
    "nets": SSHNetInfo[] | null;
}

export interface SSHDiskInfo {
    "mount": string;
    "filesystem": string;
    "fsType": string;
    "total": number;
    "used": number;
    "available": number;
    "usagePercent": number;
    "isVirtual": boolean;
}

export interface SSHDockerContainer {
    "id": string;
    "name": string;
    "image": string;
    "status": string;
    "ports": string;
    "createdAt": string;
    "running": boolean;
}

export interface SSHDockerImage {
    "id": string;
    "repo": string;
    "tag": string;
    "size": string;
    "createdAt": string;
}

export interface SSHMemInfo {
    "total": number;
    "used": number;
    "free": number;
    "available": number;
    "usagePercent": number;
    "swapTotal": number;
    "swapUsed": number;
}

export interface SSHNetInfo {
    "name": string;
    "ip": string;
    "rxBytes": number;
    "txBytes": number;
    "isLoopback": boolean;
    "isVirtual": boolean;
}

export interface SSHProcessInfo {
    "pid": number;
    "user": string;
    "cpu": number;
    "mem": number;
    "rss": number;
    "command": string;
}

export interface SSHServiceInfo {
    "name": string;
    "load": string;
    "active": string;
    "sub": string;
    "description": string;
}

/**
 * SessionInfo 是暴露给前端的会话摘要。
 */
export interface SessionInfo {
    "id": string;
    "serverId": string;
    "title": string;
    "host": string;
    "port": number;
    "username": string;
    "connected": boolean;
    "homeDir": string;
}

/**
 * Transfer 描述一个上传/下载任务。
 */
export interface Transfer {
    "id": string;
    "sessionId": string;

    /**
     * upload | download
     */
    "kind": string;
    "name": string;
    "localPath": string;
    "remotePath": string;
    "size": number;
    "transferred": number;

    /**
     * running | done | error | canceled
     */
    "status": string;
    "error": string;
    "startedAt": number;
    "updatedAt": number;
}
