// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AskRequest {
    "ask_id": string;
    "session_id": string;
    "trace_id"?: string;
    "question": string;
    "options"?: string[] | null;
    "created_at": number;
}
