// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MysqlQueryResult 表示单次 SQL 执行的统一输出。
 */
export interface MysqlQueryResult {
    "columns": string[] | null;
    "rows": ({ [_ in string]?: any } | null)[] | null;
    "affected": number;
}
