// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApiAuth 描述鉴权信息。
 */
export interface ApiAuth {
    /**
     * none | basic | bearer
     */
    "type": string;
    "username": string;
    "password": string;
    "token": string;
}

/**
 * ApiHeader 是请求头的一行，支持启用/禁用。
 */
export interface ApiHeader {
    "name": string;
    "value": string;
    "enabled": boolean;
}

/**
 * ApiRequest 描述一次 HTTP 调试请求。
 */
export interface ApiRequest {
    "method": string;
    "url": string;
    "headers": ApiHeader[] | null;
    "body": string;
    "timeoutMs": number;
    "insecureTLS": boolean;
    "followRedirects": boolean;
    "auth"?: ApiAuth | null;
}

/**
 * ApiResponse 描述一次 HTTP 调试的响应结果。
 */
export interface ApiResponse {
    "status": string;
    "statusCode": number;
    "proto": string;
    "headers": { [_ in string]?: string } | null;
    "body": string;
    "durationMs": number;
    "size": number;
    "error": string;
}

/**
 * WsConnectRequest 是建立 WebSocket 连接所需的参数
 */
export interface WsConnectRequest {
    "url": string;
    "headers": ApiHeader[] | null;
    "insecureTLS": boolean;
    "auth"?: ApiAuth | null;
    "protocols": string[] | null;
}

/**
 * WsConnectResult 是连接结果
 */
export interface WsConnectResult {
    "id": string;
    "url": string;
    "status": string;
    "error": string;
}
