// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppSettings {
    "themeMode": string;
    "fontFamily": string;
    "fontSize": string;
    "autoConnect": boolean;
    "dbDefaultLimit": string;
    "globalFontFamily": string;
    "aiBaseUrl": string;
    "aiApiKey": string;
    "aiModel": string;
    "aiTemperature": number;
    "aiMaxContextTokens": number;

    /**
     * "summary" | "sliding"
     */
    "aiCompressionStrategy": string;
    "aiEnableMultimodal": boolean;
    "aiSystemPrompt": string;
    "aiWorkspaceDir": string;
    "aiEnableWebSearch": boolean;
    "aiEnablePermissionGuard": boolean;
    "aiBlockHighRiskCommands": boolean;
    "aiEnableThinking": boolean;

    /**
     * "low" | "medium" | "high"
     */
    "aiReasoningEffort": string;
    "aiEnableVerifier": boolean;
    "aiMaxParallel": number;
}

/**
 * ServerConfig 描述一台远程服务器的连接信息。Type 字段区分 SSH / Redis / MySQL。
 */
export interface ServerConfig {
    "id": string;
    "name": string;

    /**
     * 所属分组 ID，空表示未分组
     */
    "groupId"?: string;
    "host": string;
    "port": number;
    "username": string;

    /**
     * password | key (SSH 专用)
     */
    "authType": string;
    "password": string;

    /**
     * 私钥文件路径或 PEM 内容
     */
    "privateKey": string;
    "passphrase": string;
    "remark": string;

    /**
     * ssh | redis | mysql | mqtt
     */
    "type": string;

    /**
     * Redis 数据库编号
     */
    "db"?: number;

    /**
     * Redis 高级配置
     * single | sentinel | cluster
     */
    "redisMode"?: string;

    /**
     * 哨兵地址，逗号分隔
     */
    "redisSentinels"?: string;

    /**
     * 哨兵 master 名称
     */
    "redisMasterName"?: string;

    /**
     * 集群节点，逗号分隔
     */
    "redisClusterNodes"?: string;

    /**
     * Redis 6 ACL 用户名
     */
    "redisUsername"?: string;

    /**
     * none | json
     */
    "redisSerialization"?: string;

    /**
     * 最大连接数
     */
    "redisPoolSize"?: number;

    /**
     * 最小空闲连接
     */
    "redisMinIdleConns"?: number;

    /**
     * 最大空闲连接
     */
    "redisMaxIdleConns"?: number;

    /**
     * 获取连接超时（秒）
     */
    "redisPoolTimeout"?: number;

    /**
     * 连接最大空闲时间（秒）
     */
    "redisConnMaxIdleTime"?: number;

    /**
     * 连接最大存活时间（秒）
     */
    "redisConnMaxLifetime"?: number;

    /**
     * 拨号超时（秒）
     */
    "redisDialTimeout"?: number;

    /**
     * 读超时（秒）
     */
    "redisReadTimeout"?: number;

    /**
     * 写超时（秒）
     */
    "redisWriteTimeout"?: number;

    /**
     * 命令最大重试次数
     */
    "redisMaxRetries"?: number;

    /**
     * 重试最小退避（秒）
     */
    "redisMinRetryBackoff"?: number;

    /**
     * 重试最大退避（秒）
     */
    "redisMaxRetryBackoff"?: number;

    /**
     * 熔断器打开阈值（连续失败次数）
     */
    "redisBreakerThreshold"?: number;

    /**
     * 熔断器冷却时间（秒）
     */
    "redisBreakerCooldown"?: number;

    /**
     * MySQL 高级配置
     * MySQL 默认数据库（可选）
     */
    "database"?: string;

    /**
     * 连接池最大打开连接
     */
    "mysqlMaxOpenConns"?: number;

    /**
     * 连接池最大空闲连接
     */
    "mysqlMaxIdleConns"?: number;

    /**
     * 连接最大存活（秒）
     */
    "mysqlConnMaxLifetime"?: number;

    /**
     * 空 / "true" / "skip-verify" / "preferred"
     */
    "mysqlTLS"?: string;

    /**
     * 是否启用 SSL
     */
    "mysqlSSLEnabled"?: boolean;

    /**
     * 是否启用 SSH 隧道
     */
    "mysqlSSHEnabled"?: boolean;

    /**
     * 跳板机地址
     */
    "mysqlSSHHost"?: string;

    /**
     * 跳板机端口
     */
    "mysqlSSHHostPort"?: number;

    /**
     * 跳板机用户名
     */
    "mysqlSSHUser"?: string;

    /**
     * 跳板机私钥路径
     */
    "mysqlSSHKeyPath"?: string;

    /**
     * 跳板机私钥内容
     */
    "mysqlSSHKeyData"?: string;

    /**
     * 私钥口令
     */
    "mysqlSSHPassphrase"?: string;

    /**
     * 本地监听端口（0=自动）
     */
    "mysqlSSHProxyLocalPort"?: number;

    /**
     * MongoDB 高级配置
     * 完整连接串，填写后优先生效
     */
    "mongoUri"?: string;

    /**
     * 使用 mongodb+srv:// 方案
     */
    "mongoSrv"?: boolean;

    /**
     * 多节点种子列表，逗号分隔 host:port
     */
    "mongoHosts"?: string;

    /**
     * 默认数据库
     */
    "mongoDatabase"?: string;

    /**
     * none | SCRAM-SHA-1 | SCRAM-SHA-256 | MONGODB-X509
     */
    "mongoAuthMech"?: string;

    /**
     * 认证库，默认 admin
     */
    "mongoAuthSource"?: string;

    /**
     * 副本集名称
     */
    "mongoReplicaSet"?: string;

    /**
     * primary | secondary | nearest 等
     */
    "mongoReadPreference"?: string;

    /**
     * 启用 TLS/SSL
     */
    "mongoTlsEnabled"?: boolean;

    /**
     * 跳过证书校验
     */
    "mongoTlsInsecure"?: boolean;

    /**
     * CA 证书（PEM 内容或路径）
     */
    "mongoTlsCaCert"?: string;

    /**
     * 客户端证书（X.509 认证用）
     */
    "mongoTlsClientCert"?: string;

    /**
     * 客户端私钥
     */
    "mongoTlsClientKey"?: string;

    /**
     * 连接池最大连接数
     */
    "mongoMaxPoolSize"?: number;

    /**
     * 连接池最小连接数
     */
    "mongoMinPoolSize"?: number;

    /**
     * 连接最大空闲时间（秒）
     */
    "mongoMaxConnIdleTime"?: number;

    /**
     * 连接超时（秒）
     */
    "mongoConnectTimeout"?: number;

    /**
     * 服务器选择超时（秒）
     */
    "mongoServerSelectTimeout"?: number;

    /**
     * 单次操作超时（秒）
     */
    "mongoSocketTimeout"?: number;

    /**
     * 压缩算法，逗号分隔 snappy,zlib,zstd
     */
    "mongoCompressors"?: string;

    /**
     * 上报给服务端的应用名
     */
    "mongoAppName"?: string;

    /**
     * MQTT 客户端 ID（可选）
     */
    "clientId"?: string;

    /**
     * MQTT 是否使用 TLS
     */
    "useTLS"?: boolean;

    /**
     * SQLite 本地文件配置
     * 本地 .db / .sqlite 文件路径
     */
    "sqlitePath"?: string;

    /**
     * MQTT 高级配置
     * 协议版本："3.1.1" | "3.1"
     */
    "mqttProto"?: string;

    /**
     * 心跳间隔（秒）
     */
    "mqttKeepAlive"?: number;

    /**
     * 连接超时（秒）
     */
    "mqttConnectTimeout"?: number;

    /**
     * 清除会话
     */
    "mqttCleanSession"?: boolean;

    /**
     * 自动重连
     */
    "mqttAutoReconnect"?: boolean;

    /**
     * 重连间隔（秒）
     */
    "mqttReconnectIntvl"?: number;

    /**
     * TLS 跳过证书校验
     */
    "mqttInsecure"?: boolean;

    /**
     * TLS CA 证书（PEM 内容或文件路径）
     */
    "mqttCaCert"?: string;

    /**
     * TLS 客户端证书（PEM 内容或文件路径）
     */
    "mqttClientCert"?: string;

    /**
     * TLS 客户端私钥（PEM 内容或文件路径）
     */
    "mqttClientKey"?: string;

    /**
     * 遗嘱主题
     */
    "mqttWillTopic"?: string;

    /**
     * 遗嘱消息
     */
    "mqttWillPayload"?: string;

    /**
     * 遗嘱 QoS
     */
    "mqttWillQos"?: number;

    /**
     * 遗嘱保留
     */
    "mqttWillRetained"?: boolean;
    "updatedAt": number;
}

/**
 * ServerGroup 描述服务器分组。
 */
export interface ServerGroup {
    "id": string;
    "name": string;
}
