// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppSettings {
    "themeMode": string;
    "fontFamily": string;
    "fontSize": string;
    "autoConnect": boolean;
    "dbDefaultLimit": string;
    "globalFontFamily": string;
    "aiBaseUrl": string;
    "aiApiKey": string;
    "aiModel": string;
    "aiTemperature": number;

    /**
     * 模型上下文窗口总长度 (如 131072 / 128k, 65536 / 64k)
     */
    "aiModelContextTokens": number;

    /**
     * 压缩触发百分比 (例如 80 即 80%)
     */
    "aiContextCompressRatio": number;

    /**
     * 实际触发 Token 数
     */
    "aiMaxContextTokens": number;

    /**
     * "none" | "summary" | "sliding"
     */
    "aiCompressionStrategy": string;
    "aiEnableMultimodal": boolean;
    "aiSystemPrompt": string;
    "aiWorkspaceDir": string;
    "aiEnableWebSearch": boolean;
    "aiEnablePermissionGuard": boolean;
    "aiBlockHighRiskCommands": boolean;
    "aiEnableThinking": boolean;

    /**
     * "low" | "medium" | "high"
     */
    "aiReasoningEffort": string;
    "aiEnableVerifier": boolean;
    "aiMaxParallel": number;
}

/**
 * DockerComposeRecord 描述在客户端本地保存的一个 Compose 配置文件记录。
 */
export interface DockerComposeRecord {
    /**
     * 唯一主键 UUID
     */
    "id": string;

    /**
     * 所属 Docker 实例 ID
     */
    "serverId": string;

    /**
     * Docker 项目名 (标准化小写)
     */
    "projectName": string;

    /**
     * 完整的 YAML 编排内容
     */
    "yamlContent": string;

    /**
     * 环境变量键值对
     */
    "envVars": { [_ in string]?: string } | null;

    /**
     * 创建时间
     */
    "createdAt": string;

    /**
     * 最近更新/部署时间
     */
    "updatedAt": string;
}

/**
 * ServerConfig 描述一台远程服务器的连接信息。Type 字段区分 SSH / Redis / MySQL / Docker / Postgres。
 */
export interface ServerConfig {
    "id": string;
    "name": string;

    /**
     * 所属分组 ID，空表示未分组
     */
    "groupId"?: string;
    "host": string;
    "port": number;
    "username": string;

    /**
     * password | key (SSH 专用)
     */
    "authType": string;
    "password": string;

    /**
     * 私钥文件路径或 PEM 内容
     */
    "privateKey": string;
    "passphrase": string;
    "remark": string;

    /**
     * ssh | redis | mysql | mqtt | mongo | sqlite | docker | postgres
     */
    "type": string;

    /**
     * Redis 数据库编号
     */
    "db"?: number;

    /**
     * Redis 高级配置
     * single | sentinel | cluster
     */
    "redisMode"?: string;

    /**
     * 哨兵地址，逗号分隔
     */
    "redisSentinels"?: string;

    /**
     * 哨兵 master 名称
     */
    "redisMasterName"?: string;

    /**
     * 集群节点，逗号分隔
     */
    "redisClusterNodes"?: string;

    /**
     * Redis 6 ACL 用户名
     */
    "redisUsername"?: string;

    /**
     * none | json
     */
    "redisSerialization"?: string;

    /**
     * 最大连接数
     */
    "redisPoolSize"?: number;

    /**
     * 最小空闲连接
     */
    "redisMinIdleConns"?: number;

    /**
     * 最大空闲连接
     */
    "redisMaxIdleConns"?: number;

    /**
     * 获取连接超时（秒）
     */
    "redisPoolTimeout"?: number;

    /**
     * 连接最大空闲时间（秒）
     */
    "redisConnMaxIdleTime"?: number;

    /**
     * 连接最大存活时间（秒）
     */
    "redisConnMaxLifetime"?: number;

    /**
     * 拨号超时（秒）
     */
    "redisDialTimeout"?: number;

    /**
     * 读超时（秒）
     */
    "redisReadTimeout"?: number;

    /**
     * 写超时（秒）
     */
    "redisWriteTimeout"?: number;

    /**
     * 命令最大重试次数
     */
    "redisMaxRetries"?: number;

    /**
     * 重试最小退避（秒）
     */
    "redisMinRetryBackoff"?: number;

    /**
     * 重试最大退避（秒）
     */
    "redisMaxRetryBackoff"?: number;

    /**
     * 熔断器打开阈值（连续失败次数）
     */
    "redisBreakerThreshold"?: number;

    /**
     * 熔断器冷却时间（秒）
     */
    "redisBreakerCooldown"?: number;

    /**
     * MySQL 高级配置
     * MySQL 默认数据库（可选）
     */
    "database"?: string;

    /**
     * 连接池最大打开连接
     */
    "mysqlMaxOpenConns"?: number;

    /**
     * 连接池最大空闲连接
     */
    "mysqlMaxIdleConns"?: number;

    /**
     * 连接最大存活（秒）
     */
    "mysqlConnMaxLifetime"?: number;

    /**
     * 空 / "true" / "skip-verify" / "preferred"
     */
    "mysqlTLS"?: string;

    /**
     * 是否启用 SSL
     */
    "mysqlSSLEnabled"?: boolean;

    /**
     * 是否启用 SSH 隧道
     */
    "mysqlSSHEnabled"?: boolean;

    /**
     * 跳板机地址
     */
    "mysqlSSHHost"?: string;

    /**
     * 跳板机端口
     */
    "mysqlSSHHostPort"?: number;

    /**
     * 跳板机用户名
     */
    "mysqlSSHUser"?: string;

    /**
     * 跳板机私钥路径
     */
    "mysqlSSHKeyPath"?: string;

    /**
     * 跳板机私钥内容
     */
    "mysqlSSHKeyData"?: string;

    /**
     * 私钥口令
     */
    "mysqlSSHPassphrase"?: string;

    /**
     * 本地监听端口（0=自动）
     */
    "mysqlSSHProxyLocalPort"?: number;

    /**
     * PostgreSQL 高级配置
     * 默认数据库（默认 postgres）
     */
    "postgresDatabase"?: string;

    /**
     * 默认 Schema（默认 public）
     */
    "postgresSchema"?: string;

    /**
     * disable | require | verify-ca | verify-full
     */
    "postgresSSLMode"?: string;

    /**
     * 连接池最大连接数
     */
    "postgresMaxOpenConns"?: number;

    /**
     * 最小空闲连接数
     */
    "postgresMinIdleConns"?: number;

    /**
     * 连接最大存活（秒）
     */
    "postgresConnMaxLifetime"?: number;

    /**
     * 连接最大空闲（秒）
     */
    "postgresConnMaxIdleTime"?: number;

    /**
     * 连接超时（秒）
     */
    "postgresConnectTimeout"?: number;

    /**
     * 是否启用 SSH 隧道
     */
    "postgresSSHEnabled"?: boolean;

    /**
     * 跳板机地址
     */
    "postgresSSHHost"?: string;

    /**
     * 跳板机端口
     */
    "postgresSSHHostPort"?: number;

    /**
     * 跳板机用户名
     */
    "postgresSSHUser"?: string;

    /**
     * password | key
     */
    "postgresSSHAuthType"?: string;

    /**
     * 跳板机密码
     */
    "postgresSSHPassword"?: string;

    /**
     * 跳板机私钥路径
     */
    "postgresSSHKeyPath"?: string;

    /**
     * 跳板机私钥内容
     */
    "postgresSSHKeyData"?: string;

    /**
     * 私钥口令
     */
    "postgresSSHPassphrase"?: string;

    /**
     * MongoDB 高级配置
     * 完整连接串，填写后优先生效
     */
    "mongoUri"?: string;

    /**
     * 使用 mongodb+srv:// 方案
     */
    "mongoSrv"?: boolean;

    /**
     * 多节点种子列表，逗号分隔 host:port
     */
    "mongoHosts"?: string;

    /**
     * 默认数据库
     */
    "mongoDatabase"?: string;

    /**
     * none | SCRAM-SHA-1 | SCRAM-SHA-256 | MONGODB-X509
     */
    "mongoAuthMech"?: string;

    /**
     * 认证库，默认 admin
     */
    "mongoAuthSource"?: string;

    /**
     * 副本集名称
     */
    "mongoReplicaSet"?: string;

    /**
     * primary | secondary | nearest 等
     */
    "mongoReadPreference"?: string;

    /**
     * 启用 TLS/SSL
     */
    "mongoTlsEnabled"?: boolean;

    /**
     * 跳过证书校验
     */
    "mongoTlsInsecure"?: boolean;

    /**
     * CA 证书（PEM 内容或路径）
     */
    "mongoTlsCaCert"?: string;

    /**
     * 客户端证书（X.509 认证用）
     */
    "mongoTlsClientCert"?: string;

    /**
     * 客户端私钥
     */
    "mongoTlsClientKey"?: string;

    /**
     * 连接池最大连接数
     */
    "mongoMaxPoolSize"?: number;

    /**
     * 连接池最小连接数
     */
    "mongoMinPoolSize"?: number;

    /**
     * 连接最大空闲时间（秒）
     */
    "mongoMaxConnIdleTime"?: number;

    /**
     * 连接超时（秒）
     */
    "mongoConnectTimeout"?: number;

    /**
     * 服务器选择超时（秒）
     */
    "mongoServerSelectTimeout"?: number;

    /**
     * 单次操作超时（秒）
     */
    "mongoSocketTimeout"?: number;

    /**
     * 压缩算法，逗号分隔 snappy,zlib,zstd
     */
    "mongoCompressors"?: string;

    /**
     * 上报给服务端的应用名
     */
    "mongoAppName"?: string;

    /**
     * MQTT 客户端 ID（可选）
     */
    "clientId"?: string;

    /**
     * MQTT 是否使用 TLS
     */
    "useTLS"?: boolean;

    /**
     * SQLite 本地文件配置
     * 本地 .db / .sqlite 文件路径
     */
    "sqlitePath"?: string;

    /**
     * Docker 专用配置
     * "unix" | "tcp" | "ssh"
     */
    "dockerEndpointType"?: string;

    /**
     * unix 套接字路径 (默认 /var/run/docker.sock 或 //./pipe/docker_engine)
     */
    "dockerSocketPath"?: string;

    /**
     * TCP 是否启用 TLS
     */
    "dockerTlsEnabled"?: boolean;

    /**
     * TLS 是否跳过证书校验
     */
    "dockerTlsInsecure"?: boolean;

    /**
     * TLS CA 证书
     */
    "dockerTlsCaCert"?: string;

    /**
     * TLS 客户端证书
     */
    "dockerTlsClientCert"?: string;

    /**
     * TLS 客户端私钥
     */
    "dockerTlsClientKey"?: string;

    /**
     * SSH 模式：跳板主机
     */
    "dockerSshHost"?: string;

    /**
     * SSH 模式：跳板端口 (默认 22)
     */
    "dockerSshPort"?: number;

    /**
     * SSH 模式：用户名
     */
    "dockerSshUser"?: string;

    /**
     * password | key
     */
    "dockerSshAuthType"?: string;

    /**
     * SSH 模式：密码
     */
    "dockerSshPassword"?: string;

    /**
     * SSH 模式：私钥路径
     */
    "dockerSshKeyPath"?: string;

    /**
     * SSH 模式：私钥内容
     */
    "dockerSshKeyData"?: string;

    /**
     * SSH 模式：私钥口令
     */
    "dockerSshPassphrase"?: string;

    /**
     * Kubernetes (K8s) 专用配置
     * kubeconfig | direct (默认 kubeconfig)
     */
    "k8sAuthMode"?: string;

    /**
     * Kubeconfig 文本内容 (YAML)
     */
    "k8sKubeconfigData"?: string;

    /**
     * Kubeconfig 本地文件路径
     */
    "k8sKubeconfigPath"?: string;

    /**
     * 指定 context 上下文名称（可选）
     */
    "k8sContext"?: string;

    /**
     * API Server 地址，如 https://192.168.1.100:6443
     */
    "k8sApiServer"?: string;

    /**
     * token | cert | none
     */
    "k8sAuthType"?: string;

    /**
     * Bearer Token
     */
    "k8sBearerToken"?: string;

    /**
     * CA 证书（PEM 字符串或文件路径）
     */
    "k8sCaData"?: string;

    /**
     * 客户端证书（PEM 字符串或文件路径）
     */
    "k8sCertData"?: string;

    /**
     * 客户端私钥（PEM 字符串或文件路径）
     */
    "k8sKeyData"?: string;

    /**
     * 跳过 TLS 证书校验
     */
    "k8sInsecureSkipTLS"?: boolean;

    /**
     * 默认命名空间（可选）
     */
    "k8sNamespace"?: string;

    /**
     * 是否启用 SSH 隧道代理
     */
    "k8sSshEnabled"?: boolean;

    /**
     * SSH 跳板机地址
     */
    "k8sSshHost"?: string;

    /**
     * SSH 跳板机端口 (默认 22)
     */
    "k8sSshPort"?: number;

    /**
     * SSH 用户名
     */
    "k8sSshUser"?: string;

    /**
     * password | key
     */
    "k8sSshAuthType"?: string;

    /**
     * SSH 密码
     */
    "k8sSshPassword"?: string;

    /**
     * SSH 私钥路径
     */
    "k8sSshKeyPath"?: string;

    /**
     * SSH 私钥内容
     */
    "k8sSshKeyData"?: string;

    /**
     * SSH 私钥口令
     */
    "k8sSshPassphrase"?: string;

    /**
     * MQTT 高级配置
     * 协议版本："3.1.1" | "3.1"
     */
    "mqttProto"?: string;

    /**
     * 心跳间隔（秒）
     */
    "mqttKeepAlive"?: number;

    /**
     * 连接超时（秒）
     */
    "mqttConnectTimeout"?: number;

    /**
     * 清除会话
     */
    "mqttCleanSession"?: boolean;

    /**
     * 自动重连
     */
    "mqttAutoReconnect"?: boolean;

    /**
     * 重连间隔（秒）
     */
    "mqttReconnectIntvl"?: number;

    /**
     * TLS 跳过证书校验
     */
    "mqttInsecure"?: boolean;

    /**
     * TLS CA 证书（PEM 内容或文件路径）
     */
    "mqttCaCert"?: string;

    /**
     * TLS 客户端证书（PEM 内容或文件路径）
     */
    "mqttClientCert"?: string;

    /**
     * TLS 客户端私钥（PEM 内容或文件路径）
     */
    "mqttClientKey"?: string;

    /**
     * 遗嘱主题
     */
    "mqttWillTopic"?: string;

    /**
     * 遗嘱消息
     */
    "mqttWillPayload"?: string;

    /**
     * 遗嘱 QoS
     */
    "mqttWillQos"?: number;

    /**
     * 遗嘱保留
     */
    "mqttWillRetained"?: boolean;
    "updatedAt": number;
}

/**
 * ServerGroup 描述服务器分组。
 */
export interface ServerGroup {
    "id": string;
    "name": string;
}
