// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface RedisCmdResult {
    "result": string;
    "error": string;
}

export interface RedisKeyItem {
    "key": string;
    "type": string;

    /**
     * 秒；-1 永久，-2 不存在
     */
    "ttl": number;
}

export interface RedisKeysResult {
    "keys": RedisKeyItem[] | null;
    "cursor": number;
}

export interface RedisMonitorInfo {
    "breaker": string;
    "hits": number;
    "misses": number;
    "timeouts": number;
    "totalConns": number;
    "idleConns": number;
    "staleConns": number;
    "mode": string;
    "serialization": string;
    "version"?: string;
    "memoryUsed"?: string;
    "uptimeDays"?: string;
    "connectedClients"?: string;
}

export interface RedisPipelineResult {
    "results": RedisCmdResult[] | null;
    "error": string;
}

export interface RedisQueueItem {
    "id": string;
    "payload": any;
    "empty"?: boolean;
}

export interface RedisSlowLogEntry {
    "id": number;
    "timestamp": number;
    "duration": number;
    "command": string;
    "client": string;
}

export interface RedisTransactionResult {
    "results": RedisCmdResult[] | null;
    "aborted": boolean;
    "error": string;
}

export interface RedisValue {
    "key": string;
    "type": string;
    "ttl": number;
    "value": string;
    "size": number;
    "rawJson"?: any;
}
