// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ApprovalRequest {
    "confirm_id": string;
    "session_id": string;
    "trace_id": string;
    "tool_name": string;
    "action": string;
    "path": string;
    "description": string;
    "arguments": string;
    "level": PermissionLevel;
    "created_at": number;
}

export enum PermissionLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LevelAllow = "allow",
    LevelConfirm = "confirm",
    LevelEscalate = "escalate",
    LevelForbidden = "forbidden",
};
