// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HitlRequest represents an in-flight human approval request
 */
export interface HitlRequest {
    "confirm_id": string;
    "session_id": string;
    "trace_id"?: string;
    "tool_name": string;
    "tool_desc": string;
    "input": string;
    "risk_detail": string;
    "created_at": number;
}
