// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ask$0 from "../agent/ask/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as guard$0 from "../agent/guard/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as planner$0 from "../agent/planner/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skills$0 from "../agent/skills/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../agent/store/models.js";

export function AgentAnswerAsk(askID: string, answer: string): $CancellablePromise<boolean> {
    return $Call.ByID(4268168758, askID, answer);
}

export function AgentApprovePlan(planID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3782542095, planID);
}

export function AgentCancelPlan(planID: string): $CancellablePromise<boolean> {
    return $Call.ByID(4190316478, planID);
}

export function AgentClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(1005356688);
}

export function AgentConfirmTool(confirmID: string, approved: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(214643347, confirmID, approved);
}

export function AgentCreateSession(title: string): $CancellablePromise<store$0.SessionItem | null> {
    return $Call.ByID(526240329, title);
}

export function AgentDecideApproval(confirmID: string, approved: boolean, remember: boolean, reason: string): $CancellablePromise<boolean> {
    return $Call.ByID(2014994780, confirmID, approved, remember, reason);
}

export function AgentDeleteSession(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2187831712, sessionID);
}

export function AgentGetAuditLogs(sessionID: string, limit: number): $CancellablePromise<store$0.AuditLogItem[] | null> {
    return $Call.ByID(120196687, sessionID, limit);
}

export function AgentGetHistory(): $CancellablePromise<agent$0.FrontendMessage[] | null> {
    return $Call.ByID(2067821507);
}

export function AgentGetJob(jobID: string): $CancellablePromise<store$0.JobItem | null> {
    return $Call.ByID(2411820840, jobID);
}

export function AgentGetJobOutput(jobID: string, fromSeq: number): $CancellablePromise<store$0.JobOutputItem[] | null> {
    return $Call.ByID(3833284901, jobID, fromSeq);
}

export function AgentGetPendingApprovals(): $CancellablePromise<(guard$0.ApprovalRequest | null)[] | null> {
    return $Call.ByID(3524130632);
}

export function AgentGetPendingAsks(): $CancellablePromise<(ask$0.AskRequest | null)[] | null> {
    return $Call.ByID(761804974);
}

export function AgentGetSessionMessages(sessionID: string): $CancellablePromise<agent$0.FrontendMessage[] | null> {
    return $Call.ByID(1040346779, sessionID);
}

export function AgentGetSkillsDir(): $CancellablePromise<string> {
    return $Call.ByID(740962186);
}

export function AgentGetWorkspaceDir(): $CancellablePromise<string> {
    return $Call.ByID(2272406089);
}

export function AgentInterruptSubagent(subID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3219622001, subID);
}

export function AgentKillJob(jobID: string): $CancellablePromise<boolean> {
    return $Call.ByID(174897886, jobID);
}

export function AgentListJobs(sessionID: string): $CancellablePromise<store$0.JobItem[] | null> {
    return $Call.ByID(3780268623, sessionID);
}

export function AgentListSessions(): $CancellablePromise<store$0.SessionItem[] | null> {
    return $Call.ByID(1371193518);
}

export function AgentListSkills(): $CancellablePromise<skills$0.Skill[] | null> {
    return $Call.ByID(1436024901);
}

export function AgentListSubagents(sessionID: string): $CancellablePromise<store$0.SubagentItem[] | null> {
    return $Call.ByID(644993193, sessionID);
}

export function AgentOpenSkillsDir(): $CancellablePromise<string> {
    return $Call.ByID(87494432);
}

export function AgentProposePlan(sessionID: string, objective: string): $CancellablePromise<planner$0.Plan | null> {
    return $Call.ByID(3469939612, sessionID, objective);
}

export function AgentRecallMemories(query: string, limit: number): $CancellablePromise<string[] | null> {
    return $Call.ByID(2571516017, query, limit);
}

export function AgentRetryPlanStep(planID: string, stepID: string): $CancellablePromise<planner$0.PlanStep | null> {
    return $Call.ByID(2065472082, planID, stepID);
}

export function AgentSaveHistory(messages: agent$0.FrontendMessage[] | null): $CancellablePromise<void> {
    return $Call.ByID(40985730, messages);
}

export function AgentSaveMemory(kind: string, content: string, tags: string, source: string): $CancellablePromise<void> {
    return $Call.ByID(1024061357, kind, content, tags, source);
}

export function AgentSaveSessionMessages(sessionID: string, messages: agent$0.FrontendMessage[] | null): $CancellablePromise<void> {
    return $Call.ByID(2550534882, sessionID, messages);
}

export function AgentSelectWorkspaceDir(): $CancellablePromise<string> {
    return $Call.ByID(1569351395);
}

export function AgentSend(sessionID: string, messages: agent$0.FrontendMessage[] | null): $CancellablePromise<string> {
    return $Call.ByID(2963912865, sessionID, messages);
}

export function AgentSendSubagent(subID: string, message: string): $CancellablePromise<string> {
    return $Call.ByID(3922217498, subID, message);
}

export function AgentSetWorkspaceDir(dir: string): $CancellablePromise<string> {
    return $Call.ByID(3657233765, dir);
}

export function AgentStopSend(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3629755689, sessionID);
}
