// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proto$0 from "../proto/models.js";

export function ApiRequest(req: proto$0.ApiRequest): $CancellablePromise<proto$0.ApiResponse> {
    return $Call.ByID(1541371874, req);
}

export function WsClose(id: string): $CancellablePromise<void> {
    return $Call.ByID(168471487, id);
}

export function WsConnect(req: proto$0.WsConnectRequest): $CancellablePromise<proto$0.WsConnectResult> {
    return $Call.ByID(2673553829, req);
}

export function WsSend(id: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3856359107, id, message);
}
