// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DockerService 导出给 Wails 的 Docker 管理服务接口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as docker$0 from "../docker/models.js";

/**
 * DockerClose 关闭指定 ID 的 Docker 连接。
 */
export function DockerClose(id: string): $CancellablePromise<void> {
    return $Call.ByID(2805506297, id);
}

/**
 * DockerConnect 连接指定 ID 的 Docker 实例。
 */
export function DockerConnect(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2599751095, id);
}

/**
 * DockerControlComposeStack 控制 Compose 项目（start, stop, restart, down, remove）。
 */
export function DockerControlComposeStack(id: string, projectName: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(2330972064, id, projectName, action);
}

/**
 * DockerControlContainer 控制容器生命周期（start, stop, restart, pause, unpause, remove）。
 */
export function DockerControlContainer(id: string, containerID: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(4096926827, id, containerID, action);
}

/**
 * DockerCreateContainer 创建新容器。
 */
export function DockerCreateContainer(id: string, req: docker$0.DockerCreateContainerReq): $CancellablePromise<string> {
    return $Call.ByID(424911454, id, req);
}

/**
 * DockerCreateNetwork 创建网络。
 */
export function DockerCreateNetwork(id: string, name: string, driver: string): $CancellablePromise<string> {
    return $Call.ByID(1340171675, id, name, driver);
}

/**
 * DockerCreateVolume 创建数据卷。
 */
export function DockerCreateVolume(id: string, name: string, driver: string, labels: { [_ in string]?: string } | null): $CancellablePromise<docker$0.DockerVolumeInfo | null> {
    return $Call.ByID(856910861, id, name, driver, labels);
}

/**
 * DockerDeleteComposeRecord 强力联动删除 Compose 记录（同时清理关联容器和网络）。
 */
export function DockerDeleteComposeRecord(serverId: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(2450380969, serverId, id);
}

/**
 * DockerDeployComposeStack 部署/更新 Compose 项目。
 */
export function DockerDeployComposeStack(id: string, req: docker$0.DockerComposeDeployReq): $CancellablePromise<void> {
    return $Call.ByID(2944382300, id, req);
}

/**
 * DockerExecClose 关闭指定 Docker 容器终端会话。
 */
export function DockerExecClose(execId: string): $CancellablePromise<void> {
    return $Call.ByID(448638050, execId);
}

/**
 * DockerExecResize 调整 Docker 容器终端会话行列尺寸。
 */
export function DockerExecResize(serverId: string, execId: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3289306554, serverId, execId, cols, rows);
}

/**
 * DockerExecStart 启动指定 Docker 容器的交互式终端会话。
 */
export function DockerExecStart(serverId: string, containerId: string, command: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(3746907814, serverId, containerId, command, cols, rows);
}

/**
 * DockerExecWrite 写入数据到指定 Docker 容器终端会话。
 */
export function DockerExecWrite(execId: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1583947137, execId, data);
}

/**
 * DockerGetComposeRecord 获取特定 Compose 记录详情。
 */
export function DockerGetComposeRecord(id: string): $CancellablePromise<core$0.DockerComposeRecord | null> {
    return $Call.ByID(867706746, id);
}

/**
 * DockerGetComposeStack 获取特定 Compose 项目详情。
 */
export function DockerGetComposeStack(id: string, projectName: string): $CancellablePromise<docker$0.DockerComposeStackInfo | null> {
    return $Call.ByID(1568367469, id, projectName);
}

/**
 * DockerGetComposeStackLogs 获取 Compose 项目聚合日志。
 */
export function DockerGetComposeStackLogs(id: string, projectName: string, tail: number): $CancellablePromise<string> {
    return $Call.ByID(398976142, id, projectName, tail);
}

/**
 * DockerGetContainerLogs 获取容器日志。
 */
export function DockerGetContainerLogs(id: string, containerID: string, tail: number, timestamps: boolean): $CancellablePromise<string> {
    return $Call.ByID(1630537331, id, containerID, tail, timestamps);
}

/**
 * DockerGetOverview 获取概览信息。
 */
export function DockerGetOverview(id: string): $CancellablePromise<docker$0.DockerOverview | null> {
    return $Call.ByID(1227453346, id);
}

/**
 * DockerInspectContainer 查看容器 Inspect 详情。
 */
export function DockerInspectContainer(id: string, containerID: string): $CancellablePromise<string> {
    return $Call.ByID(1320959728, id, containerID);
}

/**
 * DockerInspectImage 查看镜像 Inspect 详情。
 */
export function DockerInspectImage(id: string, imageID: string): $CancellablePromise<string> {
    return $Call.ByID(2941539666, id, imageID);
}

/**
 * DockerListComposeRecords 获取指定 Docker 服务器的本地 Compose 记录。
 */
export function DockerListComposeRecords(serverId: string): $CancellablePromise<core$0.DockerComposeRecord[] | null> {
    return $Call.ByID(823024045, serverId);
}

/**
 * DockerListComposeStacks 获取所有 Compose 项目。
 */
export function DockerListComposeStacks(id: string): $CancellablePromise<docker$0.DockerComposeStackInfo[] | null> {
    return $Call.ByID(4074609764, id);
}

/**
 * DockerListContainers 获取容器列表。
 */
export function DockerListContainers(id: string, all: boolean): $CancellablePromise<docker$0.DockerContainerInfo[] | null> {
    return $Call.ByID(3923820975, id, all);
}

/**
 * DockerListImages 获取镜像列表。
 */
export function DockerListImages(id: string): $CancellablePromise<docker$0.DockerImageInfo[] | null> {
    return $Call.ByID(432079097, id);
}

/**
 * DockerListNetworks 获取网络列表。
 */
export function DockerListNetworks(id: string): $CancellablePromise<docker$0.DockerNetworkInfo[] | null> {
    return $Call.ByID(3268779360, id);
}

/**
 * DockerListVolumes 获取数据卷列表。
 */
export function DockerListVolumes(id: string): $CancellablePromise<docker$0.DockerVolumeInfo[] | null> {
    return $Call.ByID(782015154, id);
}

/**
 * DockerLoadImage 弹出选择文件对话框并从本地 tar 包导入镜像。
 */
export function DockerLoadImage(id: string): $CancellablePromise<string> {
    return $Call.ByID(3269431192, id);
}

/**
 * DockerPing 检测连接状态。
 */
export function DockerPing(id: string): $CancellablePromise<string> {
    return $Call.ByID(674191927, id);
}

/**
 * DockerPullImage 在线拉取镜像。
 */
export function DockerPullImage(id: string, imageName: string): $CancellablePromise<string> {
    return $Call.ByID(1368296521, id, imageName);
}

/**
 * DockerRemoveImage 删除镜像。
 */
export function DockerRemoveImage(id: string, imageID: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(1169154100, id, imageID, force);
}

/**
 * DockerRemoveNetwork 删除网络。
 */
export function DockerRemoveNetwork(id: string, networkID: string): $CancellablePromise<void> {
    return $Call.ByID(1344056807, id, networkID);
}

/**
 * DockerRemoveVolume 删除数据卷。
 */
export function DockerRemoveVolume(id: string, name: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(1315696969, id, name, force);
}

/**
 * DockerSaveComposeRecord 保存/创建本地 Compose 记录。
 */
export function DockerSaveComposeRecord(record: core$0.DockerComposeRecord): $CancellablePromise<core$0.DockerComposeRecord | null> {
    return $Call.ByID(1395318731, record);
}

/**
 * DockerSaveImage 弹出保存文件对话框并将镜像导出保存为本地 tar 压缩包。
 */
export function DockerSaveImage(id: string, imageIDOrTag: string, defaultFilename: string): $CancellablePromise<string> {
    return $Call.ByID(2544736979, id, imageIDOrTag, defaultFilename);
}

/**
 * DockerSystemPrune 执行系统清理。
 */
export function DockerSystemPrune(id: string, pruneContainers: boolean, pruneImages: boolean, pruneVolumes: boolean, pruneNetworks: boolean): $CancellablePromise<docker$0.DockerPruneReport | null> {
    return $Call.ByID(320336006, id, pruneContainers, pruneImages, pruneVolumes, pruneNetworks);
}

/**
 * DockerTestConnection 测试指定配置的连通性。
 */
export function DockerTestConnection(cfg: core$0.ServerConfig): $CancellablePromise<string> {
    return $Call.ByID(4119310511, cfg);
}

/**
 * DockerUpComposeStack 执行类似 docker compose up 的智能增量更新，仅在实例创建/启动成功后才同步保存本地 YAML。
 */
export function DockerUpComposeStack(serverId: string, record: core$0.DockerComposeRecord, forcePull: boolean, recreate: boolean): $CancellablePromise<core$0.DockerComposeRecord | null> {
    return $Call.ByID(2251632454, serverId, record, forcePull, recreate);
}
