// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * K8sService 导出给 Wails 的 Kubernetes 集群管理服务接口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as k8s$0 from "../k8s/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * K8sApplyOrchestration 部署并保存 Kubernetes YAML 编排。严格遵循后验强一致性：先部署，成功后再落盘。
 */
export function K8sApplyOrchestration(serverId: string, record: core$0.K8sOrchestrationRecord): $CancellablePromise<k8s$0.K8sApplyResult[] | null> {
    return $Call.ByID(819612696, serverId, record);
}

/**
 * K8sApplyYAML 声明式部署并应用 YAML 资源清单。
 */
export function K8sApplyYAML(id: string, yamlContent: string): $CancellablePromise<k8s$0.K8sApplyResult[] | null> {
    return $Call.ByID(2998105980, id, yamlContent);
}

/**
 * K8sClose 关闭指定 ID 的 K8s 连接。
 */
export function K8sClose(id: string): $CancellablePromise<void> {
    return $Call.ByID(1637713187, id);
}

/**
 * K8sConnect 连接指定 ID 的 K8s 集群。
 */
export function K8sConnect(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(761603833, id);
}

/**
 * K8sCreateNamespace 创建新命名空间。
 */
export function K8sCreateNamespace(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2955191656, id, name);
}

/**
 * K8sDeleteConfigMap 删除指定 ConfigMap。
 */
export function K8sDeleteConfigMap(id: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1972333994, id, $namespace, name);
}

/**
 * K8sDeleteDeployment 删除指定 Deployment。
 */
export function K8sDeleteDeployment(id: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(611026257, id, $namespace, name);
}

/**
 * K8sDeleteIngress 删除指定 Ingress。
 */
export function K8sDeleteIngress(id: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2609698145, id, $namespace, name);
}

/**
 * K8sDeleteNamespace 删除指定命名空间。
 */
export function K8sDeleteNamespace(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1692489681, id, name);
}

/**
 * K8sDeleteOrchestrationRecordOnly 仅删除本地编排记录，不下线集群中的资源。
 */
export function K8sDeleteOrchestrationRecordOnly(recordId: string): $CancellablePromise<void> {
    return $Call.ByID(597004804, recordId);
}

/**
 * K8sDeletePVC 删除指定 PVC。
 */
export function K8sDeletePVC(id: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1150001905, id, $namespace, name);
}

/**
 * K8sDeletePod 删除指定 Pod。
 */
export function K8sDeletePod(id: string, $namespace: string, podName: string): $CancellablePromise<void> {
    return $Call.ByID(990087765, id, $namespace, podName);
}

/**
 * K8sDeleteSecret 删除指定 Secret。
 */
export function K8sDeleteSecret(id: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1288634778, id, $namespace, name);
}

/**
 * K8sDeleteService 删除指定 Service。
 */
export function K8sDeleteService(id: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3349422065, id, $namespace, name);
}

/**
 * K8sDeleteYAML 声明式删除并下线 YAML 资源清单中的资源。
 */
export function K8sDeleteYAML(id: string, yamlContent: string): $CancellablePromise<k8s$0.K8sDeleteResult[] | null> {
    return $Call.ByID(3261434137, id, yamlContent);
}

/**
 * K8sExecClose 关闭指定终端会话。
 */
export function K8sExecClose(execID: string): $CancellablePromise<void> {
    return $Call.ByID(1884949952, execID);
}

/**
 * K8sExecResize 调整终端会话尺寸。
 */
export function K8sExecResize(execID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(1447709684, execID, cols, rows);
}

/**
 * K8sExecStart 启动指定 Pod 容器的交互式终端会话。
 */
export function K8sExecStart(id: string, $namespace: string, podName: string, container: string, command: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(1916866256, id, $namespace, podName, container, command, cols, rows);
}

/**
 * K8sExecWrite 写入数据到指定终端会话。
 */
export function K8sExecWrite(execID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(847452779, execID, data);
}

/**
 * K8sGenerateYAML 使用专职 Agent 生成 Kubernetes YAML 配置。
 */
export function K8sGenerateYAML(req: $models.K8sGenerateYAMLRequest): $CancellablePromise<string> {
    return $Call.ByID(1902076433, req);
}

/**
 * K8sGetOrchestrationRecord 获取单个 K8s 编排记录详情。
 */
export function K8sGetOrchestrationRecord(id: string): $CancellablePromise<core$0.K8sOrchestrationRecord | null> {
    return $Call.ByID(2076350265, id);
}

/**
 * K8sGetOverview 获取集群概览。
 */
export function K8sGetOverview(id: string): $CancellablePromise<k8s$0.K8sOverview | null> {
    return $Call.ByID(2800887056, id);
}

/**
 * K8sGetPodLogs 获取 Pod 容器日志。
 */
export function K8sGetPodLogs(id: string, $namespace: string, podName: string, containerName: string, tail: number, timestamps: boolean): $CancellablePromise<string> {
    return $Call.ByID(2086029237, id, $namespace, podName, containerName, tail, timestamps);
}

/**
 * K8sGetResourceYAML 获取指定资源的 YAML 文本。
 */
export function K8sGetResourceYAML(id: string, kind: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1268476180, id, kind, $namespace, name);
}

/**
 * K8sListConfigMaps 获取 ConfigMap 列表。
 */
export function K8sListConfigMaps(id: string, $namespace: string): $CancellablePromise<k8s$0.K8sConfigMapInfo[] | null> {
    return $Call.ByID(38720192, id, $namespace);
}

/**
 * K8sListDeployments 获取 Deployment 列表。
 */
export function K8sListDeployments(id: string, $namespace: string): $CancellablePromise<k8s$0.K8sDeploymentInfo[] | null> {
    return $Call.ByID(778830219, id, $namespace);
}

/**
 * K8sListIngresses 获取 Ingress 列表。
 */
export function K8sListIngresses(id: string, $namespace: string): $CancellablePromise<k8s$0.K8sIngressInfo[] | null> {
    return $Call.ByID(2840591328, id, $namespace);
}

/**
 * K8sListNamespaces 获取所有命名空间。
 */
export function K8sListNamespaces(id: string): $CancellablePromise<k8s$0.K8sNamespaceInfo[] | null> {
    return $Call.ByID(658906885, id);
}

/**
 * K8sListNodes 获取所有节点。
 */
export function K8sListNodes(id: string): $CancellablePromise<k8s$0.K8sNodeInfo[] | null> {
    return $Call.ByID(452994830, id);
}

/**
 * K8sListOrchestrationRecords 获取指定集群本地持久化存储的 K8s 编排记录。
 */
export function K8sListOrchestrationRecords(serverId: string): $CancellablePromise<core$0.K8sOrchestrationRecord[] | null> {
    return $Call.ByID(416016864, serverId);
}

/**
 * K8sListPVCs 获取 PVC 列表。
 */
export function K8sListPVCs(id: string, $namespace: string): $CancellablePromise<k8s$0.K8sPVCInfo[] | null> {
    return $Call.ByID(2819681845, id, $namespace);
}

/**
 * K8sListPods 获取指定命名空间（或全量）的 Pod 列表。
 */
export function K8sListPods(id: string, $namespace: string): $CancellablePromise<k8s$0.K8sPodInfo[] | null> {
    return $Call.ByID(1784011433, id, $namespace);
}

/**
 * K8sListSecrets 获取 Secret 列表。
 */
export function K8sListSecrets(id: string, $namespace: string): $CancellablePromise<k8s$0.K8sSecretInfo[] | null> {
    return $Call.ByID(2137589570, id, $namespace);
}

/**
 * K8sListServices 获取 Service 列表。
 */
export function K8sListServices(id: string, $namespace: string): $CancellablePromise<k8s$0.K8sServiceInfo[] | null> {
    return $Call.ByID(1254326489, id, $namespace);
}

/**
 * K8sOfflineOrchestration 下线指定的编排资源，支持同时删除本地记录或标记为已下线。
 */
export function K8sOfflineOrchestration(serverId: string, recordId: string, deleteLocalFile: boolean): $CancellablePromise<k8s$0.K8sDeleteResult[] | null> {
    return $Call.ByID(848722473, serverId, recordId, deleteLocalFile);
}

/**
 * K8sParseKubeconfig 解析 Kubeconfig 文本或文件获取上下文列表。
 */
export function K8sParseKubeconfig(kubeconfigData: string, kubeconfigPath: string): $CancellablePromise<k8s$0.KubeconfigContextInfo | null> {
    return $Call.ByID(1146715323, kubeconfigData, kubeconfigPath);
}

/**
 * K8sPing 检测连接状态。
 */
export function K8sPing(id: string): $CancellablePromise<string> {
    return $Call.ByID(207142537, id);
}

/**
 * K8sRestartDeployment 触发 Deployment 滚动重启。
 */
export function K8sRestartDeployment(id: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3716675843, id, $namespace, name);
}

/**
 * K8sScaleDeployment 动态调整 Deployment 副本数。
 */
export function K8sScaleDeployment(id: string, $namespace: string, name: string, replicas: number): $CancellablePromise<void> {
    return $Call.ByID(3071594666, id, $namespace, name, replicas);
}

/**
 * K8sTestConnection 测试指定配置的连通性。
 */
export function K8sTestConnection(cfg: core$0.ServerConfig): $CancellablePromise<string> {
    return $Call.ByID(3832172761, cfg);
}
