// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DockerGenerateComposeRequest 描述 AI 生成 Docker Compose 请求参数。
 */
export interface DockerGenerateComposeRequest {
    "images": string[] | null;
    "prompt": string;
}

/**
 * K8sGenerateYAMLRequest 描述 AI 生成 YAML 请求参数。
 */
export interface K8sGenerateYAMLRequest {
    "namespace": string;
    "kinds": string[] | null;
    "images": string[] | null;
    "prompt": string;
}
