// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mongo$0 from "../mongo/models.js";

export function MongoAggregate(id: string, dbName: string, coll: string, pipelineJSON: string, allowDiskUse: boolean, maxTimeMS: number): $CancellablePromise<mongo$0.MongoFindResult> {
    return $Call.ByID(3809732088, id, dbName, coll, pipelineJSON, allowDiskUse, maxTimeMS);
}

export function MongoAggregateExplain(id: string, dbName: string, coll: string, pipelineJSON: string): $CancellablePromise<string> {
    return $Call.ByID(4168453327, id, dbName, coll, pipelineJSON);
}

export function MongoBulkWrite(id: string, dbName: string, coll: string, ops: mongo$0.MongoBulkOp[] | null, ordered: boolean): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(287098676, id, dbName, coll, ops, ordered);
}

export function MongoClientStats(id: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1923382133, id);
}

export function MongoClose(id: string): $CancellablePromise<void> {
    return $Call.ByID(431906195, id);
}

export function MongoCollectionStats(id: string, dbName: string, coll: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(320211696, id, dbName, coll);
}

export function MongoCollections(id: string, dbName: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(719384470, id, dbName);
}

export function MongoConnect(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2942794601, id);
}

export function MongoCountDocuments(id: string, dbName: string, coll: string, filterJSON: string): $CancellablePromise<number> {
    return $Call.ByID(2926069346, id, dbName, coll, filterJSON);
}

export function MongoCreateCollection(id: string, dbName: string, coll: string): $CancellablePromise<void> {
    return $Call.ByID(935981625, id, dbName, coll);
}

export function MongoCreateDatabase(id: string, dbName: string, firstCollection: string): $CancellablePromise<void> {
    return $Call.ByID(3469255360, id, dbName, firstCollection);
}

export function MongoCreateIndex(id: string, dbName: string, coll: string, keysJSON: string, name: string, unique: boolean, sparse: boolean, expireAfterSeconds: number): $CancellablePromise<string> {
    return $Call.ByID(411226355, id, dbName, coll, keysJSON, name, unique, sparse, expireAfterSeconds);
}

export function MongoCurrentOps(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2734184362, id);
}

export function MongoDatabases(id: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(3752666561, id);
}

export function MongoDeleteMany(id: string, dbName: string, coll: string, filterJSON: string): $CancellablePromise<number> {
    return $Call.ByID(1816990397, id, dbName, coll, filterJSON);
}

export function MongoDeleteOne(id: string, dbName: string, coll: string, filterJSON: string): $CancellablePromise<number> {
    return $Call.ByID(3112279266, id, dbName, coll, filterJSON);
}

export function MongoDistinct(id: string, dbName: string, coll: string, field: string, filterJSON: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2696432029, id, dbName, coll, field, filterJSON);
}

export function MongoDropCollection(id: string, dbName: string, coll: string): $CancellablePromise<void> {
    return $Call.ByID(2894013280, id, dbName, coll);
}

export function MongoDropDatabase(id: string, dbName: string): $CancellablePromise<void> {
    return $Call.ByID(3966734769, id, dbName);
}

export function MongoDropIndex(id: string, dbName: string, coll: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2160040248, id, dbName, coll, name);
}

export function MongoExplain(id: string, spec: mongo$0.MongoQuerySpec, verbosity: string): $CancellablePromise<string> {
    return $Call.ByID(901413100, id, spec, verbosity);
}

export function MongoFind(id: string, spec: mongo$0.MongoQuerySpec): $CancellablePromise<mongo$0.MongoFindResult> {
    return $Call.ByID(3716934922, id, spec);
}

export function MongoFindOneAndUpdate(id: string, dbName: string, coll: string, filterJSON: string, updateJSON: string, returnNew: boolean): $CancellablePromise<string> {
    return $Call.ByID(2539216562, id, dbName, coll, filterJSON, updateJSON, returnNew);
}

export function MongoGetValidator(id: string, dbName: string, coll: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2183260459, id, dbName, coll);
}

export function MongoHealthCheck(id: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3132008081, id);
}

export function MongoIndexStats(id: string, dbName: string, coll: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1536820550, id, dbName, coll);
}

export function MongoIndexes(id: string, dbName: string, coll: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(3907454859, id, dbName, coll);
}

export function MongoInferSchema(id: string, dbName: string, coll: string, sampleSize: number): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(2502065264, id, dbName, coll, sampleSize);
}

export function MongoInsertMany(id: string, dbName: string, coll: string, docsJSON: string, ordered: boolean): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2889472911, id, dbName, coll, docsJSON, ordered);
}

export function MongoInsertOne(id: string, dbName: string, coll: string, docJSON: string): $CancellablePromise<string> {
    return $Call.ByID(3728221068, id, dbName, coll, docJSON);
}

export function MongoParseURI(uri: string): $CancellablePromise<mongo$0.MongoURIInfo> {
    return $Call.ByID(907933238, uri);
}

export function MongoRenameCollection(id: string, dbName: string, coll: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2321072987, id, dbName, coll, newName);
}

export function MongoReplaceOne(id: string, dbName: string, coll: string, filterJSON: string, docJSON: string, upsert: boolean): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1439479857, id, dbName, coll, filterJSON, docJSON, upsert);
}

export function MongoRunCommand(id: string, dbName: string, commandJSON: string): $CancellablePromise<string> {
    return $Call.ByID(481433675, id, dbName, commandJSON);
}

export function MongoServerStatus(id: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2809245196, id);
}

export function MongoSetValidator(id: string, dbName: string, coll: string, validatorJSON: string, level: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(3176020167, id, dbName, coll, validatorJSON, level, action);
}

export function MongoTestConnection(cfg: core$0.ServerConfig): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1305815945, cfg);
}

export function MongoTransaction(id: string, ops: mongo$0.MongoTxOp[] | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2239110451, id, ops);
}

export function MongoUnwatch(id: string, watchKey: string): $CancellablePromise<void> {
    return $Call.ByID(4272295409, id, watchKey);
}

export function MongoUpdateMany(id: string, dbName: string, coll: string, filterJSON: string, updateJSON: string, upsert: boolean): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1155622123, id, dbName, coll, filterJSON, updateJSON, upsert);
}

export function MongoUpdateOne(id: string, dbName: string, coll: string, filterJSON: string, updateJSON: string, upsert: boolean): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2043631192, id, dbName, coll, filterJSON, updateJSON, upsert);
}

export function MongoValidateDocument(id: string, dbName: string, coll: string, docJSON: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3729000414, id, dbName, coll, docJSON);
}

export function MongoWatch(id: string, scope: string, dbName: string, coll: string, pipelineJSON: string, fullDocument: string): $CancellablePromise<string> {
    return $Call.ByID(2067847864, id, scope, dbName, coll, pipelineJSON, fullDocument);
}

export function MongoWatchList(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1606688224, id);
}
