// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

export function MqttClose(id: string): $CancellablePromise<void> {
    return $Call.ByID(2410213577, id);
}

export function MqttConnect(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1899099655, id);
}

export function MqttPublish(id: string, topic: string, payload: string, qos: number, retained: boolean): $CancellablePromise<void> {
    return $Call.ByID(3483724146, id, topic, payload, qos, retained);
}

export function MqttSubscribe(id: string, topic: string, qos: number): $CancellablePromise<void> {
    return $Call.ByID(1172909037, id, topic, qos);
}

export function MqttSubscriptions(id: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(624402751, id);
}

export function MqttTestConnection(cfg: core$0.ServerConfig): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(917389567, cfg);
}

export function MqttUnsubscribe(id: string, topic: string): $CancellablePromise<void> {
    return $Call.ByID(3789405396, id, topic);
}
