// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export function MysqlBackup(serverID: string, dbName: string): $CancellablePromise<string> {
    return $Call.ByID(579540003, serverID, dbName);
}

export function MysqlBackupToFile(serverID: string, dbName: string): $CancellablePromise<string> {
    return $Call.ByID(439329384, serverID, dbName);
}

export function MysqlChangeUserPassword(serverID: string, user: string, host: string, newPassword: string): $CancellablePromise<void> {
    return $Call.ByID(384986867, serverID, user, host, newPassword);
}

export function MysqlClose(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(1174544751, serverID);
}

export function MysqlConnect(serverID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1255425557, serverID);
}

export function MysqlCount(serverID: string, dbName: string, table: string): $CancellablePromise<number> {
    return $Call.ByID(631298840, serverID, dbName, table);
}

export function MysqlCreateDatabase(serverID: string, name: string, charset: string): $CancellablePromise<void> {
    return $Call.ByID(3940872268, serverID, name, charset);
}

export function MysqlCreateIndex(serverID: string, dbName: string, table: string, name: string, colsCSV: string, unique: boolean): $CancellablePromise<void> {
    return $Call.ByID(2272130823, serverID, dbName, table, name, colsCSV, unique);
}

export function MysqlCreateTable(serverID: string, dbName: string, table: string, defs: string): $CancellablePromise<void> {
    return $Call.ByID(1655247275, serverID, dbName, table, defs);
}

export function MysqlCreateUser(serverID: string, user: string, host: string, password: string, authPlugin: string, lock: boolean): $CancellablePromise<void> {
    return $Call.ByID(2910165566, serverID, user, host, password, authPlugin, lock);
}

export function MysqlDatabases(serverID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3535624445, serverID);
}

export function MysqlDelete(serverID: string, dbName: string, table: string, whereCols: string[] | null, whereVals: any[] | null): $CancellablePromise<number> {
    return $Call.ByID(3933970934, serverID, dbName, table, whereCols, whereVals);
}

export function MysqlDescribe(serverID: string, dbName: string, table: string): $CancellablePromise<db$0.MysqlQueryResult> {
    return $Call.ByID(440693212, serverID, dbName, table);
}

export function MysqlDropDatabase(serverID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1441536981, serverID, name);
}

export function MysqlDropIndex(serverID: string, dbName: string, table: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2828420900, serverID, dbName, table, name);
}

export function MysqlDropTable(serverID: string, dbName: string, table: string): $CancellablePromise<void> {
    return $Call.ByID(4069156652, serverID, dbName, table);
}

export function MysqlDropUser(serverID: string, user: string, host: string): $CancellablePromise<void> {
    return $Call.ByID(626115403, serverID, user, host);
}

export function MysqlExport(serverID: string, dbName: string, mode: string, source: string, table: string, sqlText: string, limit: number): $CancellablePromise<string> {
    return $Call.ByID(393135543, serverID, dbName, mode, source, table, sqlText, limit);
}

export function MysqlExportJSON(serverID: string, dbName: string, source: string, table: string, sqlText: string, limit: number): $CancellablePromise<string> {
    return $Call.ByID(1206214917, serverID, dbName, source, table, sqlText, limit);
}

export function MysqlExportToFile(serverID: string, dbName: string, mode: string, source: string, table: string, sqlText: string, limit: number): $CancellablePromise<string> {
    return $Call.ByID(1321013220, serverID, dbName, mode, source, table, sqlText, limit);
}

export function MysqlGrantPrivileges(serverID: string, user: string, host: string, dbName: string, table: string, privs: string[] | null, withGrantOption: boolean): $CancellablePromise<void> {
    return $Call.ByID(3872778457, serverID, user, host, dbName, table, privs, withGrantOption);
}

export function MysqlGrants(serverID: string, user: string, host: string): $CancellablePromise<string> {
    return $Call.ByID(4691246, serverID, user, host);
}

export function MysqlImport(serverID: string, dbName: string, mode: string, table: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(2463796664, serverID, dbName, mode, table, content);
}

export function MysqlImportFromFile(serverID: string, dbName: string, mode: string, table: string): $CancellablePromise<string> {
    return $Call.ByID(177428350, serverID, dbName, mode, table);
}

export function MysqlImportJSON(serverID: string, dbName: string, table: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(3162791866, serverID, dbName, table, content);
}

export function MysqlIndexes(serverID: string, dbName: string, table: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(362807455, serverID, dbName, table);
}

export function MysqlInsert(serverID: string, dbName: string, table: string, columns: string[] | null, values: any[] | null): $CancellablePromise<number> {
    return $Call.ByID(1196097948, serverID, dbName, table, columns, values);
}

export function MysqlProcessList(serverID: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(4066607066, serverID);
}

export function MysqlQueryCSV(serverID: string, dbName: string, sqlText: string, limit: number): $CancellablePromise<string> {
    return $Call.ByID(838869649, serverID, dbName, sqlText, limit);
}

export function MysqlRevokeAllPrivileges(serverID: string, user: string, host: string): $CancellablePromise<void> {
    return $Call.ByID(2066560698, serverID, user, host);
}

export function MysqlRevokePrivileges(serverID: string, user: string, host: string, dbName: string, table: string, privs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3115807327, serverID, user, host, dbName, table, privs);
}

export function MysqlRun(serverID: string, dbName: string, sqlText: string): $CancellablePromise<db$0.MysqlQueryResult> {
    return $Call.ByID(968298446, serverID, dbName, sqlText);
}

export function MysqlSchema(serverID: string, dbName: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(95102882, serverID, dbName);
}

export function MysqlSelect(serverID: string, dbName: string, table: string, limit: number, offset: number): $CancellablePromise<db$0.MysqlQueryResult> {
    return $Call.ByID(3813520953, serverID, dbName, table, limit, offset);
}

export function MysqlSlowLog(serverID: string, limit: number): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(1466844398, serverID, limit);
}

export function MysqlStatus(serverID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(907222243, serverID);
}

export function MysqlTableStatus(serverID: string, dbName: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(1214044397, serverID, dbName);
}

export function MysqlTables(serverID: string, dbName: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(870810776, serverID, dbName);
}

export function MysqlTestConnection(cfg: core$0.ServerConfig): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3058496949, cfg);
}

export function MysqlToggleUserLock(serverID: string, user: string, host: string, lock: boolean): $CancellablePromise<void> {
    return $Call.ByID(2170285001, serverID, user, host, lock);
}

export function MysqlTruncateTable(serverID: string, dbName: string, table: string): $CancellablePromise<void> {
    return $Call.ByID(2402059821, serverID, dbName, table);
}

export function MysqlUpdate(serverID: string, dbName: string, table: string, setCols: string[] | null, setVals: any[] | null, whereCols: string[] | null, whereVals: any[] | null): $CancellablePromise<number> {
    return $Call.ByID(4036253216, serverID, dbName, table, setCols, setVals, whereCols, whereVals);
}

export function MysqlUsers(serverID: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(3320548199, serverID);
}

export function MysqlVariables(serverID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2702344654, serverID);
}
