// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export function PostgresClose(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(3027666641, serverID);
}

export function PostgresConnect(serverID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1667745183, serverID);
}

export function PostgresCount(serverID: string, dbName: string, schema: string, table: string, whereClause: string): $CancellablePromise<number> {
    return $Call.ByID(1260114234, serverID, dbName, schema, table, whereClause);
}

export function PostgresCreateDatabase(serverID: string, name: string, owner: string, encoding: string, template: string): $CancellablePromise<void> {
    return $Call.ByID(1382147790, serverID, name, owner, encoding, template);
}

export function PostgresCreateRole(serverID: string, roleName: string, password: string, $super: boolean, canLogin: boolean, createDB: boolean, createRole: boolean, connLimit: number): $CancellablePromise<void> {
    return $Call.ByID(3601783199, serverID, roleName, password, $super, canLogin, createDB, createRole, connLimit);
}

export function PostgresCreateSchema(serverID: string, dbName: string, schema: string, owner: string): $CancellablePromise<void> {
    return $Call.ByID(1406440588, serverID, dbName, schema, owner);
}

export function PostgresCreateTable(serverID: string, dbName: string, schema: string, table: string, defs: string): $CancellablePromise<void> {
    return $Call.ByID(1292583229, serverID, dbName, schema, table, defs);
}

export function PostgresDatabases(serverID: string): $CancellablePromise<db$0.PgDatabase[] | null> {
    return $Call.ByID(449337431, serverID);
}

export function PostgresDelete(serverID: string, dbName: string, schema: string, table: string, whereCols: string[] | null, whereVals: any[] | null): $CancellablePromise<number> {
    return $Call.ByID(4056032120, serverID, dbName, schema, table, whereCols, whereVals);
}

export function PostgresDescribe(serverID: string, dbName: string, schema: string, table: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1993031478, serverID, dbName, schema, table);
}

export function PostgresDropDatabase(serverID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(581870303, serverID, name);
}

export function PostgresDropRole(serverID: string, roleName: string): $CancellablePromise<void> {
    return $Call.ByID(3004592754, serverID, roleName);
}

export function PostgresDropSchema(serverID: string, dbName: string, schema: string, cascade: boolean): $CancellablePromise<void> {
    return $Call.ByID(4083492925, serverID, dbName, schema, cascade);
}

export function PostgresDropTable(serverID: string, dbName: string, schema: string, table: string, cascade: boolean): $CancellablePromise<void> {
    return $Call.ByID(2659005734, serverID, dbName, schema, table, cascade);
}

export function PostgresExplain(serverID: string, dbName: string, sqlText: string, analyze: boolean, buffers: boolean, verbose: boolean): $CancellablePromise<string> {
    return $Call.ByID(2834951298, serverID, dbName, sqlText, analyze, buffers, verbose);
}

export function PostgresExport(serverID: string, dbName: string, schema: string, mode: string, source: string, table: string, sqlText: string, limit: number): $CancellablePromise<string> {
    return $Call.ByID(1872119489, serverID, dbName, schema, mode, source, table, sqlText, limit);
}

export function PostgresExportToFile(serverID: string, dbName: string, schema: string, mode: string, source: string, table: string, sqlText: string, limit: number): $CancellablePromise<string> {
    return $Call.ByID(1506876310, serverID, dbName, schema, mode, source, table, sqlText, limit);
}

export function PostgresFunctions(serverID: string, dbName: string, schema: string): $CancellablePromise<db$0.PgFunction[] | null> {
    return $Call.ByID(1135313736, serverID, dbName, schema);
}

export function PostgresGrantPrivileges(serverID: string, dbName: string, roleName: string, schema: string, table: string, privileges: string, isGrant: boolean): $CancellablePromise<void> {
    return $Call.ByID(870162299, serverID, dbName, roleName, schema, table, privileges, isGrant);
}

export function PostgresImport(serverID: string, dbName: string, schema: string, mode: string, table: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(4003920178, serverID, dbName, schema, mode, table, content);
}

export function PostgresImportFromFile(serverID: string, dbName: string, schema: string, mode: string, table: string): $CancellablePromise<string> {
    return $Call.ByID(3460303984, serverID, dbName, schema, mode, table);
}

export function PostgresInsert(serverID: string, dbName: string, schema: string, table: string, columns: string[] | null, values: any[] | null): $CancellablePromise<number> {
    return $Call.ByID(1217134714, serverID, dbName, schema, table, columns, values);
}

export function PostgresKillSession(serverID: string, dbName: string, pid: number, terminate: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(842213173, serverID, dbName, pid, terminate);
}

export function PostgresRoles(serverID: string): $CancellablePromise<db$0.PgRole[] | null> {
    return $Call.ByID(1236675636, serverID);
}

export function PostgresRun(serverID: string, dbName: string, sqlText: string): $CancellablePromise<db$0.PostgresQueryResult> {
    return $Call.ByID(35376300, serverID, dbName, sqlText);
}

export function PostgresSchemas(serverID: string, dbName: string): $CancellablePromise<db$0.PgSchema[] | null> {
    return $Call.ByID(3602461981, serverID, dbName);
}

export function PostgresSelect(serverID: string, dbName: string, schema: string, table: string, limit: number, offset: number, sortCol: string, sortOrder: string, whereClause: string): $CancellablePromise<db$0.PostgresQueryResult> {
    return $Call.ByID(2671027211, serverID, dbName, schema, table, limit, offset, sortCol, sortOrder, whereClause);
}

export function PostgresSequences(serverID: string, dbName: string, schema: string): $CancellablePromise<db$0.PgSequence[] | null> {
    return $Call.ByID(4041483995, serverID, dbName, schema);
}

export function PostgresSessions(serverID: string, dbName: string): $CancellablePromise<db$0.PgSession[] | null> {
    return $Call.ByID(14253138, serverID, dbName);
}

export function PostgresStatus(serverID: string, dbName: string): $CancellablePromise<db$0.PgStatus> {
    return $Call.ByID(2879645501, serverID, dbName);
}

export function PostgresTableDDL(serverID: string, dbName: string, schema: string, table: string): $CancellablePromise<string> {
    return $Call.ByID(3053588451, serverID, dbName, schema, table);
}

export function PostgresTables(serverID: string, dbName: string, schema: string): $CancellablePromise<db$0.PgTable[] | null> {
    return $Call.ByID(2631621146, serverID, dbName, schema);
}

export function PostgresTestConnection(cfg: core$0.ServerConfig): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3632021687, cfg);
}

export function PostgresTruncateTable(serverID: string, dbName: string, schema: string, table: string, restartIdentity: boolean, cascade: boolean): $CancellablePromise<void> {
    return $Call.ByID(2987398851, serverID, dbName, schema, table, restartIdentity, cascade);
}

export function PostgresUpdate(serverID: string, dbName: string, schema: string, table: string, setCols: string[] | null, setVals: any[] | null, whereCols: string[] | null, whereVals: any[] | null): $CancellablePromise<number> {
    return $Call.ByID(1218229066, serverID, dbName, schema, table, setCols, setVals, whereCols, whereVals);
}

export function PostgresUpdateRolePassword(serverID: string, roleName: string, newPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2324663015, serverID, roleName, newPassword);
}
