// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as redis$0 from "../redis/models.js";

export function RedisClose(id: string): $CancellablePromise<void> {
    return $Call.ByID(3394587209, id);
}

export function RedisConnect(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1468640135, id);
}

export function RedisDBSize(id: string): $CancellablePromise<number> {
    return $Call.ByID(1475888396, id);
}

export function RedisDelete(id: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(3488248304, id, key);
}

export function RedisExpire(id: string, key: string, ttl: number): $CancellablePromise<void> {
    return $Call.ByID(4273100524, id, key, ttl);
}

export function RedisGet(id: string, key: string): $CancellablePromise<redis$0.RedisValue> {
    return $Call.ByID(1333871869, id, key);
}

export function RedisHashFieldDel(id: string, key: string, fields: string[] | null): $CancellablePromise<number> {
    return $Call.ByID(2485896338, id, key, fields);
}

export function RedisHashFieldGet(id: string, key: string, field: string): $CancellablePromise<string> {
    return $Call.ByID(117686063, id, key, field);
}

export function RedisHashFieldSet(id: string, key: string, field: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2568797755, id, key, field, value);
}

export function RedisInfo(id: string, section: string): $CancellablePromise<string> {
    return $Call.ByID(1795807431, id, section);
}

export function RedisKeys(id: string, pattern: string, cursor: string): $CancellablePromise<redis$0.RedisKeysResult> {
    return $Call.ByID(941224795, id, pattern, cursor);
}

export function RedisKeyspaceNotify(id: string, db: number, event: string): $CancellablePromise<void> {
    return $Call.ByID(4125599197, id, db, event);
}

export function RedisListPop(id: string, key: string, left: boolean): $CancellablePromise<string> {
    return $Call.ByID(256249406, id, key, left);
}

export function RedisListPush(id: string, key: string, value: string, left: boolean): $CancellablePromise<number> {
    return $Call.ByID(839654751, id, key, value, left);
}

export function RedisModeInfo(id: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4006371584, id);
}

export function RedisMonitor(id: string): $CancellablePromise<redis$0.RedisMonitorInfo | null> {
    return $Call.ByID(1329631539, id);
}

export function RedisPSubscribe(id: string, pattern: string): $CancellablePromise<void> {
    return $Call.ByID(2910252127, id, pattern);
}

export function RedisPipeline(id: string, commands: string[] | null): $CancellablePromise<redis$0.RedisPipelineResult> {
    return $Call.ByID(164353629, id, commands);
}

export function RedisPublish(id: string, channel: string, message: string): $CancellablePromise<number> {
    return $Call.ByID(3053264626, id, channel, message);
}

export function RedisQueueDequeue(id: string, queue: string, mode: string, timeout: number): $CancellablePromise<redis$0.RedisQueueItem | null> {
    return $Call.ByID(665847288, id, queue, mode, timeout);
}

export function RedisQueueEnqueue(id: string, queue: string, payload: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(1597927724, id, queue, payload, mode);
}

export function RedisQueueLength(id: string, queue: string, mode: string): $CancellablePromise<number> {
    return $Call.ByID(1258488102, id, queue, mode);
}

export function RedisRaw(id: string, cmd: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(692209427, id, cmd);
}

export function RedisSelectDB(id: string, db: number): $CancellablePromise<void> {
    return $Call.ByID(2988606821, id, db);
}

export function RedisSet(id: string, key: string, typ: string, val: string, ttl: number): $CancellablePromise<void> {
    return $Call.ByID(3479860177, id, key, typ, val, ttl);
}

export function RedisSetAdd(id: string, key: string, members: string[] | null): $CancellablePromise<number> {
    return $Call.ByID(1521937928, id, key, members);
}

export function RedisSetRem(id: string, key: string, members: string[] | null): $CancellablePromise<number> {
    return $Call.ByID(3422356027, id, key, members);
}

export function RedisSlowLog(id: string, count: number): $CancellablePromise<redis$0.RedisSlowLogEntry[] | null> {
    return $Call.ByID(3665374936, id, count);
}

export function RedisStringAppend(id: string, key: string, value: string): $CancellablePromise<number> {
    return $Call.ByID(3482042114, id, key, value);
}

export function RedisSubscribe(id: string, channel: string): $CancellablePromise<void> {
    return $Call.ByID(4150369645, id, channel);
}

export function RedisSubscriptions(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(338012863, id);
}

export function RedisTestConnection(cfg: core$0.ServerConfig): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3613865343, cfg);
}

export function RedisTransaction(id: string, watch: string[] | null, commands: string[] | null): $CancellablePromise<redis$0.RedisTransactionResult> {
    return $Call.ByID(3836761829, id, watch, commands);
}

export function RedisUnsubscribe(id: string, channel: string): $CancellablePromise<void> {
    return $Call.ByID(4116400724, id, channel);
}

export function RedisZSetAdd(id: string, key: string, member: string, score: number): $CancellablePromise<number> {
    return $Call.ByID(1603934208, id, key, member, score);
}

export function RedisZSetRem(id: string, key: string, members: string[] | null): $CancellablePromise<number> {
    return $Call.ByID(14710723, id, key, members);
}
