// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

export function CancelTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(4127284595, id);
}

export function ChooseLocalFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3063354741);
}

export function ChooseLocalFolder(): $CancellablePromise<string> {
    return $Call.ByID(2653061674);
}

export function ClearFinishedTransfers(): $CancellablePromise<void> {
    return $Call.ByID(1513193999);
}

export function DownloadPaths(sessionID: string, remotePaths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3738390982, sessionID, remotePaths);
}

export function DownloadTo(sessionID: string, remotePaths: string[] | null, localDir: string): $CancellablePromise<void> {
    return $Call.ByID(3535962535, sessionID, remotePaths, localDir);
}

export function HomeDir(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(2235440748, sessionID);
}

export function ListDir(sessionID: string, dir: string): $CancellablePromise<ssh$0.DirListing> {
    return $Call.ByID(999765429, sessionID, dir);
}

export function ListTransfers(): $CancellablePromise<ssh$0.Transfer[] | null> {
    return $Call.ByID(1534918834);
}

export function MakeDir(sessionID: string, parent: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2012357359, sessionID, parent, name);
}

export function ReadLocalFile(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(2811581031, filePath);
}

export function ReadLocalFileBase64(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(3246886144, filePath);
}

export function ReadRemoteFile(sessionID: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(3488543862, sessionID, remotePath);
}

export function RemovePath(sessionID: string, target: string): $CancellablePromise<void> {
    return $Call.ByID(2568987565, sessionID, target);
}

export function RemovePaths(sessionID: string, targets: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3939432058, sessionID, targets);
}

export function RenamePath(sessionID: string, target: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(853623147, sessionID, target, newName);
}

export function SaveMysqlFile(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(2613390649, defaultName);
}

export function UploadData(sessionID: string, remoteDir: string, name: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(294845087, sessionID, remoteDir, name, base64Data);
}

export function UploadPaths(sessionID: string, remoteDir: string, localPaths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2842966921, sessionID, remoteDir, localPaths);
}

export function WriteLocalFile(filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3496488838, filePath, content);
}

export function WriteRemoteFile(sessionID: string, remotePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(999941941, sessionID, remotePath, content);
}
