// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function SqliteClose(id: string): $CancellablePromise<void> {
    return $Call.ByID(3627431669, id);
}

export function SqliteConnect(id: string, filePath: string): $CancellablePromise<boolean> {
    return $Call.ByID(1582738259, id, filePath);
}

export function SqliteCount(id: string, table: string): $CancellablePromise<number> {
    return $Call.ByID(1324275382, id, table);
}

export function SqliteDescribe(id: string, table: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(2771097954, id, table);
}

export function SqliteIndexes(id: string, table: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(3368192025, id, table);
}

export function SqliteInfo(id: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3390329019, id);
}

export function SqliteOpenFile(): $CancellablePromise<string> {
    return $Call.ByID(2228180493);
}

export function SqliteRun(id: string, sqlText: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2058116680, id, sqlText);
}

export function SqliteSchema(id: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1872133072, id);
}

export function SqliteSelect(id: string, table: string, limit: number, offset: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3852992543, id, table, limit, offset);
}

export function SqliteTables(id: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(2499628438, id);
}
