// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

export function Connect(serverID: string, cols: number, rows: number): $CancellablePromise<ssh$0.SessionInfo> {
    return $Call.ByID(788030449, serverID, cols, rows);
}

export function ConnectWithConfig(cfg: core$0.ServerConfig, cols: number, rows: number): $CancellablePromise<ssh$0.SessionInfo> {
    return $Call.ByID(3610390663, cfg, cols, rows);
}

export function Disconnect(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3779980835, sessionID);
}

export function ListSessions(): $CancellablePromise<ssh$0.SessionInfo[] | null> {
    return $Call.ByID(1298673048);
}

export function ResizeTerminal(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(1572386637, sessionID, cols, rows);
}

export function SSHControlService(sessionID: string, serviceName: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(1845503529, sessionID, serviceName, action);
}

export function SSHCronList(sessionID: string): $CancellablePromise<ssh$0.SSHCronItem[] | null> {
    return $Call.ByID(3618916809, sessionID);
}

export function SSHDashboardStats(sessionID: string): $CancellablePromise<ssh$0.SSHDashboardInfo | null> {
    return $Call.ByID(2656132434, sessionID);
}

export function SSHDockerContainerList(sessionID: string): $CancellablePromise<ssh$0.SSHDockerContainer[] | null> {
    return $Call.ByID(1639180020, sessionID);
}

export function SSHDockerContainerLogs(sessionID: string, containerID: string, tail: number): $CancellablePromise<string> {
    return $Call.ByID(4136830599, sessionID, containerID, tail);
}

export function SSHDockerControlContainer(sessionID: string, containerID: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(3213963537, sessionID, containerID, action);
}

export function SSHDockerImageList(sessionID: string): $CancellablePromise<ssh$0.SSHDockerImage[] | null> {
    return $Call.ByID(3920102122, sessionID);
}

export function SSHDockerPullImage(sessionID: string, imageName: string): $CancellablePromise<string> {
    return $Call.ByID(2328790751, sessionID, imageName);
}

export function SSHDockerRemoveImage(sessionID: string, imageID: string): $CancellablePromise<void> {
    return $Call.ByID(603304526, sessionID, imageID);
}

export function SSHKillProcess(sessionID: string, pid: number): $CancellablePromise<void> {
    return $Call.ByID(1155799794, sessionID, pid);
}

export function SSHProcessList(sessionID: string): $CancellablePromise<ssh$0.SSHProcessInfo[] | null> {
    return $Call.ByID(720724354, sessionID);
}

export function SSHRunCronCommand(sessionID: string, command: string): $CancellablePromise<string> {
    return $Call.ByID(2227318083, sessionID, command);
}

export function SSHSaveCronList(sessionID: string, items: ssh$0.SSHCronItem[] | null): $CancellablePromise<void> {
    return $Call.ByID(468750592, sessionID, items);
}

export function SSHServiceList(sessionID: string): $CancellablePromise<ssh$0.SSHServiceInfo[] | null> {
    return $Call.ByID(2374008576, sessionID);
}

export function SSHServiceLogs(sessionID: string, serviceName: string): $CancellablePromise<string> {
    return $Call.ByID(3275651899, sessionID, serviceName);
}

export function SendInput(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(350783029, sessionID, data);
}
