// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(1243504996, id);
}

export function DeleteServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(4081336458, id);
}

export function GetAppSettings(): $CancellablePromise<core$0.AppSettings> {
    return $Call.ByID(3489392456);
}

export function ListGroups(): $CancellablePromise<core$0.ServerGroup[] | null> {
    return $Call.ByID(3810483558);
}

export function ListServers(): $CancellablePromise<core$0.ServerConfig[] | null> {
    return $Call.ByID(2746994206);
}

export function MoveServerToGroup(serverID: string, groupID: string): $CancellablePromise<void> {
    return $Call.ByID(1292569476, serverID, groupID);
}

export function SaveAppSettings(settings: core$0.AppSettings): $CancellablePromise<core$0.AppSettings> {
    return $Call.ByID(3625395103, settings);
}

export function SaveGroup(g: core$0.ServerGroup): $CancellablePromise<core$0.ServerGroup> {
    return $Call.ByID(2147344438, g);
}

export function SaveServer(cfg: core$0.ServerConfig): $CancellablePromise<core$0.ServerConfig> {
    return $Call.ByID(325269124, cfg);
}

export function SelectCertFile(): $CancellablePromise<string> {
    return $Call.ByID(3499346898);
}

export function SelectLocalSqliteFile(): $CancellablePromise<string> {
    return $Call.ByID(686355551);
}

export function SelectPrivateKey(): $CancellablePromise<string> {
    return $Call.ByID(2287002800);
}
