// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WikiService 提供给前端 Wails 绑定的知识库管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wiki$0 from "../agent/wiki/models.js";

/**
 * CompileSessionToWiki 调用大模型提炼会话中的关键资产，并自动合并更新到 Wiki
 */
export function CompileSessionToWiki(sessionID: string, messages: agent$0.FrontendMessage[] | null): $CancellablePromise<string> {
    return $Call.ByID(1883329833, sessionID, messages);
}

/**
 * CreateWikiNode 创建文档或分组
 */
export function CreateWikiNode(parentPath: string, name: string, isFolder: boolean): $CancellablePromise<string> {
    return $Call.ByID(3737923895, parentPath, name, isFolder);
}

/**
 * DeleteWikiNode 删除文档或分组
 */
export function DeleteWikiNode(relPath: string): $CancellablePromise<void> {
    return $Call.ByID(183983360, relPath);
}

/**
 * GetWikiCatalog 获取知识库紧凑目录与摘要
 */
export function GetWikiCatalog(): $CancellablePromise<wiki$0.WikiCatalogItem[] | null> {
    return $Call.ByID(3693254844);
}

/**
 * GetWikiDir 获取本地 Wiki 根目录
 */
export function GetWikiDir(): $CancellablePromise<string> {
    return $Call.ByID(3819667872);
}

/**
 * ListWikiTree 列出知识库文档树
 */
export function ListWikiTree(): $CancellablePromise<wiki$0.WikiNode[] | null> {
    return $Call.ByID(921259459);
}

/**
 * OpenWikiDir 打开本地系统文件浏览器
 */
export function OpenWikiDir(): $CancellablePromise<void> {
    return $Call.ByID(3240566234);
}

/**
 * ReadWikiPage 读取指定相对路径的 Markdown 内容
 */
export function ReadWikiPage(relPath: string): $CancellablePromise<string> {
    return $Call.ByID(938498600, relPath);
}

/**
 * RenameWikiNode 重命名或移动文档/分组
 */
export function RenameWikiNode(oldRelPath: string, newRelPath: string): $CancellablePromise<void> {
    return $Call.ByID(1511964989, oldRelPath, newRelPath);
}

/**
 * SaveWikiPage 保存 Markdown 页面
 */
export function SaveWikiPage(relPath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3170522057, relPath, content);
}
