// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "./tools/models.js";

export type ActiveConnectionInfo = tools$0.ActiveConnectionInfo;

export interface FrontendMessage {
    "role": string;
    "content": string;
    "reasoning_content"?: string;
    "process_steps"?: ProcessStep[] | null;
    "images"?: string[] | null;
    "tool_calls"?: ToolCallItem[] | null;
    "tool_call_id"?: string;
    "name"?: string;
    "timestamp"?: number;
}

export interface ProcessStep {
    "id": string;

    /**
     * "think" | "tool"
     */
    "type": string;
    "title": string;
    "summary"?: string;
    "content": string;
    "timestamp": number;
    "duration_ms"?: number;
    "status"?: string;
}

export interface ToolCallItem {
    "id": string;
    "name": string;
    "args": string;
}
