// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApiRequest(arg1) {
  return window['go']['main']['App']['ApiRequest'](arg1);
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ChooseLocalFiles() {
  return window['go']['main']['App']['ChooseLocalFiles']();
}

export function ChooseLocalFolder() {
  return window['go']['main']['App']['ChooseLocalFolder']();
}

export function ClearFinishedTransfers() {
  return window['go']['main']['App']['ClearFinishedTransfers']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function ConnectWithConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectWithConfig'](arg1, arg2, arg3);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DownloadPaths(arg1, arg2) {
  return window['go']['main']['App']['DownloadPaths'](arg1, arg2);
}

export function DownloadTo(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadTo'](arg1, arg2, arg3);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function HomeDir(arg1) {
  return window['go']['main']['App']['HomeDir'](arg1);
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTransfers() {
  return window['go']['main']['App']['ListTransfers']();
}

export function MakeDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['MakeDir'](arg1, arg2, arg3);
}

export function MoveServerToGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveServerToGroup'](arg1, arg2);
}

export function ReadLocalFile(arg1) {
  return window['go']['main']['App']['ReadLocalFile'](arg1);
}

export function ReadLocalFileBase64(arg1) {
  return window['go']['main']['App']['ReadLocalFileBase64'](arg1);
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRemoteFile'](arg1, arg2);
}

export function RemovePath(arg1, arg2) {
  return window['go']['main']['App']['RemovePath'](arg1, arg2);
}

export function RemovePaths(arg1, arg2) {
  return window['go']['main']['App']['RemovePaths'](arg1, arg2);
}

export function RenamePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SSHControlService(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHControlService'](arg1, arg2, arg3);
}

export function SSHCronList(arg1) {
  return window['go']['main']['App']['SSHCronList'](arg1);
}

export function SSHDashboardStats(arg1) {
  return window['go']['main']['App']['SSHDashboardStats'](arg1);
}

export function SSHDockerContainerList(arg1) {
  return window['go']['main']['App']['SSHDockerContainerList'](arg1);
}

export function SSHDockerContainerLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHDockerContainerLogs'](arg1, arg2, arg3);
}

export function SSHDockerControlContainer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHDockerControlContainer'](arg1, arg2, arg3);
}

export function SSHDockerImageList(arg1) {
  return window['go']['main']['App']['SSHDockerImageList'](arg1);
}

export function SSHDockerPullImage(arg1, arg2) {
  return window['go']['main']['App']['SSHDockerPullImage'](arg1, arg2);
}

export function SSHDockerRemoveImage(arg1, arg2) {
  return window['go']['main']['App']['SSHDockerRemoveImage'](arg1, arg2);
}

export function SSHKillProcess(arg1, arg2) {
  return window['go']['main']['App']['SSHKillProcess'](arg1, arg2);
}

export function SSHProcessList(arg1) {
  return window['go']['main']['App']['SSHProcessList'](arg1);
}

export function SSHRunCronCommand(arg1, arg2) {
  return window['go']['main']['App']['SSHRunCronCommand'](arg1, arg2);
}

export function SSHSaveCronList(arg1, arg2) {
  return window['go']['main']['App']['SSHSaveCronList'](arg1, arg2);
}

export function SSHServiceList(arg1) {
  return window['go']['main']['App']['SSHServiceList'](arg1);
}

export function SSHServiceLogs(arg1, arg2) {
  return window['go']['main']['App']['SSHServiceLogs'](arg1, arg2);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveGroup(arg1) {
  return window['go']['main']['App']['SaveGroup'](arg1);
}

export function SaveMysqlFile(arg1) {
  return window['go']['main']['App']['SaveMysqlFile'](arg1);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SelectPrivateKey() {
  return window['go']['main']['App']['SelectPrivateKey']();
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function UploadData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadData'](arg1, arg2, arg3, arg4);
}

export function UploadPaths(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadPaths'](arg1, arg2, arg3);
}

export function WriteLocalFile(arg1, arg2) {
  return window['go']['main']['App']['WriteLocalFile'](arg1, arg2);
}

export function WriteRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteRemoteFile'](arg1, arg2, arg3);
}

export function WsClose(arg1) {
  return window['go']['main']['App']['WsClose'](arg1);
}

export function WsConnect(arg1) {
  return window['go']['main']['App']['WsConnect'](arg1);
}

export function WsSend(arg1, arg2) {
  return window['go']['main']['App']['WsSend'](arg1, arg2);
}
