// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';
import {ssh} from '../models';
import {core} from '../models';

export function ApiRequest(arg1:proto.ApiRequest):Promise<proto.ApiResponse>;

export function CancelTransfer(arg1:string):Promise<void>;

export function ChooseLocalFiles():Promise<Array<string>>;

export function ChooseLocalFolder():Promise<string>;

export function ClearFinishedTransfers():Promise<void>;

export function Connect(arg1:string,arg2:number,arg3:number):Promise<ssh.SessionInfo>;

export function ConnectWithConfig(arg1:core.ServerConfig,arg2:number,arg3:number):Promise<ssh.SessionInfo>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadPaths(arg1:string,arg2:Array<string>):Promise<void>;

export function DownloadTo(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function GetAppSettings():Promise<core.AppSettings>;

export function HomeDir(arg1:string):Promise<string>;

export function ListDir(arg1:string,arg2:string):Promise<ssh.DirListing>;

export function ListGroups():Promise<Array<core.ServerGroup>>;

export function ListServers():Promise<Array<core.ServerConfig>>;

export function ListSessions():Promise<Array<ssh.SessionInfo>>;

export function ListTransfers():Promise<Array<ssh.Transfer>>;

export function MakeDir(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveServerToGroup(arg1:string,arg2:string):Promise<void>;

export function ReadLocalFile(arg1:string):Promise<string>;

export function ReadLocalFileBase64(arg1:string):Promise<string>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function RemovePath(arg1:string,arg2:string):Promise<void>;

export function RemovePaths(arg1:string,arg2:Array<string>):Promise<void>;

export function RenamePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SSHControlService(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SSHCronList(arg1:string):Promise<Array<ssh.SSHCronItem>>;

export function SSHDashboardStats(arg1:string):Promise<ssh.SSHDashboardInfo>;

export function SSHDockerContainerList(arg1:string):Promise<Array<ssh.SSHDockerContainer>>;

export function SSHDockerContainerLogs(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SSHDockerControlContainer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SSHDockerImageList(arg1:string):Promise<Array<ssh.SSHDockerImage>>;

export function SSHDockerPullImage(arg1:string,arg2:string):Promise<string>;

export function SSHDockerRemoveImage(arg1:string,arg2:string):Promise<void>;

export function SSHKillProcess(arg1:string,arg2:number):Promise<void>;

export function SSHProcessList(arg1:string):Promise<Array<ssh.SSHProcessInfo>>;

export function SSHRunCronCommand(arg1:string,arg2:string):Promise<string>;

export function SSHSaveCronList(arg1:string,arg2:Array<ssh.SSHCronItem>):Promise<void>;

export function SSHServiceList(arg1:string):Promise<Array<ssh.SSHServiceInfo>>;

export function SSHServiceLogs(arg1:string,arg2:string):Promise<string>;

export function SaveAppSettings(arg1:core.AppSettings):Promise<core.AppSettings>;

export function SaveGroup(arg1:core.ServerGroup):Promise<core.ServerGroup>;

export function SaveMysqlFile(arg1:string):Promise<string>;

export function SaveServer(arg1:core.ServerConfig):Promise<core.ServerConfig>;

export function SelectPrivateKey():Promise<string>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function UploadData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadPaths(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function WriteLocalFile(arg1:string,arg2:string):Promise<void>;

export function WriteRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WsClose(arg1:string):Promise<void>;

export function WsConnect(arg1:proto.WsConnectRequest):Promise<proto.WsConnectResult>;

export function WsSend(arg1:string,arg2:string):Promise<void>;
