// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActiveConnectionInfo {
    /**
     * ssh, redis, mysql, postgres, mongo, sqlite, docker, k8s, mqtt
     */
    "protocol": string;

    /**
     * 连接 ID / Session ID
     */
    "id": string;

    /**
     * 会话/连接名称
     */
    "name": string;

    /**
     * 主机地址
     */
    "host"?: string;

    /**
     * 端口
     */
    "port"?: number;

    /**
     * 数据库名 / Redis DB
     */
    "database"?: string;

    /**
     * K8s 命名空间
     */
    "namespace"?: string;

    /**
     * 连接用户
     */
    "username"?: string;

    /**
     * SQLite 路径
     */
    "path"?: string;
}
